### PR TITLE
Make it possible to remove backend from director

### LINKED ISSUE #545: Unable to remove backends from director
### Terraform Version

Terraform v1.1.6
on darwin_amd64
provider registry.terraform.io/fastly/fastly v1.0.0

### Affected Resource(s)

`backends` attribute in the `director` block.

### Steps to Reproduce

First, apply the following

```hcl
resource "fastly_service_vcl" "test" {
  name = "test"

  domain {
    name    = "test.example.com"
  }

  backend {
    name    = "b1"
    address = "127.0.0.1"
    port = 80
  }

  backend {
    name    = "b2"
    address = "127.0.0.1"
    port = 80
  }

  director {
    name = "director"
    backends = [ "b1", "b2" ]
  }
}
```

Then apply the following.

```hcl
resource "fastly_service_vcl" "test" {
  name = "test"

  domain {
    name    = "test.example.com"
  }

  backend {
    name    = "b1"
    address = "127.0.0.1"
    port = 80
  }

  backend {
    name    = "b2"
    address = "127.0.0.1"
    port = 80
  }

  director {
    name = "director"
    backends = [ "b1" ]
  }
}
```

### Expected Behavior

`b2` is removed from backends.

### Actual Behavior

`terraform apply` succeeds but `b2` remains in the Fastly service.

### Workaround

Delete it manually using the endpoint.
https://developer.fastly.com/reference/api/load-balancing/directors/backend/#delete-director-backend

### LINKED ISSUE #546: null in the comment field causes configuration drift
### Terraform Version

Terraform v1.1.6
on darwin_amd64
provider registry.terraform.io/fastly/fastly v1.0.0

### Affected Resource(s)

`director` block in `fastly_service_vcl`.

### Steps to Reproduce

1. First apply the following

```hcl
resource "fastly_service_vcl" "test" {
  name = "test"

  domain {
    name    = "test.example.com"
  }

  backend {
    name    = "b1"
    address = "127.0.0.1"
    port = 80
  }

  director {
    name = "director1"
    backends = [ "b1" ]
  }

  force_destroy = true
}
```

2. Apply the following.

```hcl
resource "fastly_service_vcl" "test" {
  name = "test"

  domain {
    name    = "test.example.com"
  }

  backend {
    name    = "b1"
    address = "127.0.0.1"
    port = 80
  }

  backend {
    name    = "b2"
    address = "127.0.0.1"
    port = 80
  }

  director {
    name = "director1"
    backends = [ "b1" ]
  }

  director {
    name = "director2"
    backends = [ "b2" ]
  }

  force_destroy = true
}
```

3. `terraform plan`. Terraform detects states drift for `director1`.

```hcl
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # fastly_service_vcl.test has changed
  ~ resource "fastly_service_vcl" "test" {
        id                 = "1pZgyKfHom2bni2f3lHRZf"
        name               = "test"
        # (8 unchanged attributes hidden)


      + director {
          + backends = [
              + "b1",
            ]
          + name     = "director1"
          + quorum   = 75
          + retries  = 5
          + type     = 1
        }
      - director {
          - backends = [
              - "b1",
            ] -> null
          - name     = "director1" -> null
          - quorum   = 75 -> null
          - retries  = 5 -> null
          - type     = 1 -> null
        }

        # (4 unchanged blocks hidden)
    }
```

With `TF_LOG=warn`, the following message appears on step 3.

```
2022-02-19T17:43:27.805+0900 [WARN]  Provider "registry.terraform.io/fastly/fastly" produced an unexpected new value for fastly_service_vcl.test during refresh.
      - .director: planned set element cty.ObjectVal(map[string]cty.Value{"backends":cty.SetVal([]cty.Value{cty.StringVal("b1")}), "comment":cty.NullVal(cty.String), "name":cty.StringVal("director1"), "quorum":cty.NumberIntVal(75), "retries":cty.NumberIntVal(5), "shield":cty.StringVal(""), "type":cty.NumberIntVal(1)}) does not correlate with any element in actual
```

### Some Findings

This is related to the comment attribute in the director block.
After step 1, the comment is set to `""` in the state file.

```json
"director": [
    {
    "backends": [
        "b1"
    ],
    "comment": "",    <<
    "name": "director1",
```

After step 2, the comment value is replaced with null.

```json
"director": [
    {
    "backends": [
        "b1"
    ],
    "comment": null,    <<
    "name": "director1",
```

If you manually change the comment field back to `""`, Terraform stops detecting the drift.
The issue doesn't occur if the default value of the comment field is set to `""` in the schema.

### PR DESCRIPTION
**Pull request by hrmsk66**
Fixes https://github.com/fastly/terraform-provider-fastly/issues/545
Fixes https://github.com/fastly/terraform-provider-fastly/issues/546

Make it possible to remove backends from a director.

This is a proposed fix for #545
If the backend in a director block changes, get the changes from `*schema.ResourceData` and compute backends to be removed/added using Set's `Difference` method.

Removing a director backend can result in a 404 error if the backend is removed from the service. I'm just ignoring the error in this fix since they don't mean anything useful to users.

I've also fixed an unrelated issue (#546) with the comment field in the director block which was causing the acceptance tests to fail.

### CODE REVIEW

File: fastly/block_fastly_service_director_test.go [hunk 1]
```diff
@@ -114,6 +114,11 @@ func TestResourceFastlyFlattenDirectors(t *testing.T) {
 	}
 }
 
+// This test validates that two directors are created successfully,
+// and in the next Terraform run the first director is updated while
+// the second director is unchanged and a third director is added.
+// In the final test, the first director is removed while the second
+// director is unchanged and one backend for the third director is removed.
 func TestAccFastlyServiceVCL_directors_basic(t *testing.T) {
```
Comment (Integralist) [inline fastly/block_fastly_service_director_test.go:122]: ❤️ 

I always appreciate when people take the time to provide a 'summary' of a test.

File: fastly/block_fastly_service_director.go [hunk 2]
```diff
@@ -301,3 +318,31 @@ func flattenDirectors(directorList []*gofastly.Director, directorBackendList []*
 	}
 	return dl
 }
+
+func getDirectorBackendChange(d *schema.ResourceData, resource map[string]interface{}) (odb *schema.Set, ndb *schema.Set) {
```
Comment (Integralist) [inline fastly/block_fastly_service_director.go:322]: Just to double check: are we not able to reuse https://github.com/fastly/terraform-provider-fastly/blob/256c95df476fd53628927a086122178b5df0b65b/fastly/diff.go#L52 ?

File: fastly/block_fastly_service_director.go [hunk 3]
```diff
@@ -301,3 +318,31 @@ func flattenDirectors(directorList []*gofastly.Director, directorBackendList []*
...
+	name := resource["name"]
```
Comment (Integralist) [inline fastly/block_fastly_service_director.go]: I'd prefer to keep the variable initialisation near to where it is used (see the following suggested change).

```suggestion
```

File: fastly/block_fastly_service_director.go [hunk 4]
```diff
@@ -301,3 +318,31 @@ func flattenDirectors(directorList []*gofastly.Director, directorBackendList []*
...
+			director := director.(map[string]interface{})
+
+			if director["name"] == targetDirectorName {
+				return director["backends"].(*schema.Set)
+			}
+		}
+		return new(schema.Set)
+	}
+
+	odb = get(name.(string), od.(*schema.Set))
```
Comment (Integralist) [inline fastly/block_fastly_service_director.go:344]:
```suggestion
	name := resource["name"]
	odb = get(name.(string), od.(*schema.Set))
```

**Review by Integralist — APPROVED** [review]
A couple of comments but otherwise LGTM.

**Comment by Integralist** [comment]
Also @hrmsk66 can you run `make generate-docs`

File: fastly/block_fastly_service_director.go (hunk 2 above)
Comment (hrmsk66) [reply fastly/block_fastly_service_director.go:322]: The **Diff** method cannot replace **getDirectorBackendChange()**. To my understanding, **Diff** is handling a different issue:

- The **Diff** method takes two Set objects and converts them into a DiffResult object containing the Added, Modified, Deleted, and Unmodified lists.
- **getDirectorBackendChange()** gets Director Set objects from `*schema.ResourceData`, iterate over them to find the changed Director, then extract Director Backend Set objects from the Director Set and return them. (Basically, it returns child Set objects extracted from parent Set objects)

**Review by Integralist — APPROVED** [review]
