### PR TITLE
s3logging: default S3 domain to s3.amazonaws.com to match api default

### LINKED ISSUE #10: s3logging changes on each apply even if HCL did not change
### Terraform Version

0.9.9

### Affected Resource(s)

- fastly_service_v1

### Terraform Configuration Files

```hcl
...
  # NOTE: This config defines the S3 destination, but no
  # logging happens here (it's done in custom VCL)
  s3logging {
    name               = "S3 Logs"
    bucket_name        = "my_bucket"
    s3_access_key      = "foo"
    s3_secret_key      = "bar"
    path               = "logs/fastly/"
    period             = "900"
    gzip_level         = "1"
    response_condition = "Priority 20 Always False"
    format             = "%h %l %u %t %r %>s req.http.x-log-host resp.http.X-Cache req.http.x-forwarded-for req.http.range"
  }
...
```

### Debug Output
```
~ fastly_service_v1.pl
    s3logging.1412920004.bucket_name:        "" => "my_bucket"
    s3logging.1412920004.domain:             "" => ""
    s3logging.1412920004.format:             "" => "%h %l %u %t %r %>s req.http.x-log-host resp.http.X-Cache req.http.x-forwarded-for req.http.range"
    s3logging.1412920004.format_version:     "" => "1"
    s3logging.1412920004.gzip_level:         "" => "1"
    s3logging.1412920004.name:               "" => "S3 Logs"
    s3logging.1412920004.path:               "" => "logs/fastly/"
    s3logging.1412920004.period:             "" => "900"
    s3logging.1412920004.response_condition: "" => "Priority 20 Always False"
    s3logging.1412920004.s3_access_key:      "<sensitive>" => "<sensitive>" (attribute changed)
    s3logging.1412920004.s3_secret_key:      "<sensitive>" => "<sensitive>" (attribute changed)
    s3logging.1412920004.timestamp_format:   "" => "%Y-%m-%dT%H:%M:%S.000"
    s3logging.3742254017.bucket_name:        "my_bucket" => ""
    s3logging.3742254017.domain:             "s3.amazonaws.com" => ""
    s3logging.3742254017.format:             "%h %l %u %t %r %>s req.http.x-log-host resp.http.X-Cache req.http.x-forwarded-for req.http.range" => ""
    s3logging.3742254017.format_version:     "1" => "0"
    s3logging.3742254017.gzip_level:         "1" => "0"
    s3logging.3742254017.name:               "S3 Logs" => ""
    s3logging.3742254017.path:               "logs/fastly/" => ""
    s3logging.3742254017.period:             "900" => "0"
    s3logging.3742254017.response_condition: "Priority 20 Always False" => ""
    s3logging.3742254017.s3_access_key:      "" => ""
    s3logging.3742254017.s3_secret_key:      "" => ""
    s3logging.3742254017.timestamp_format:   "%Y-%m-%dT%H:%M:%S.000" => ""
```
### Panic Output

n/a

### Expected Behavior

The resource should not be changed

### Actual Behavior

Terraform changes the resources, even though the contents of the old and new resources are the same.

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids

n/a

### References
- hashicorp/terraform#8916

cc @catsby, we just talked about this during the break in your presentation at Altitude

### PR DESCRIPTION
**Pull request by catsby**
Set default value for the `domain` attribute in the `s3logging` block. Right now if it's not in us-east-1, you need to specify a value, but it seems now that the API will provide a default of `s3.amazonaws.com` so we need to match it.

Users specifying any valid value are unaffected, and users without a value are seeing a perpetual diff, so this should be fine in terms of backwards compatibility regarding the struct hash. 

All our existing tests supplied a value here, so I add a new test with that uses the default.

```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./fastly -v -run=TestAccFastlyServiceV1_s3logging -timeout 120m
=== RUN   TestAccFastlyServiceV1_s3logging_basic
--- PASS: TestAccFastlyServiceV1_s3logging_basic (33.43s)
=== RUN   TestAccFastlyServiceV1_s3logging_domain_default
--- PASS: TestAccFastlyServiceV1_s3logging_domain_default (15.20s)
=== RUN   TestAccFastlyServiceV1_s3logging_s3_env
--- PASS: TestAccFastlyServiceV1_s3logging_s3_env (16.60s)
=== RUN   TestAccFastlyServiceV1_s3logging_formatVersion
--- PASS: TestAccFastlyServiceV1_s3logging_formatVersion (14.53s)
PASS
ok      github.com/terraform-providers/terraform-provider-fastly/fastly 79.774s
```

Should fix #10 /cc @DanielRussell

### CODE REVIEW

File: fastly/resource_fastly_service_v1_s3logging_test.go [hunk 1]
```diff
@@ -78,6 +78,46 @@ func TestAccFastlyServiceV1_s3logging_basic(t *testing.T) {
...
+			{
+				Config: testAccServiceV1S3LoggingConfig_domain_default(name, domainName1),
+				Check: resource.ComposeTestCheckFunc(
+					testAccCheckServiceV1Exists("fastly_service_v1.foo", &service),
+					testAccCheckFastlyServiceV1S3LoggingAttributes(&service, []*gofastly.S3{&log1}),
+					resource.TestCheckResourceAttr(
+						"fastly_service_v1.foo", "name", name),
+					resource.TestCheckResourceAttr(
+						"fastly_service_v1.foo", "s3logging.#", "1"),
+				),
```
Comment (radeksimko) [inline fastly/resource_fastly_service_v1_s3logging_test.go]: I guess we could also check that new default value of `s3logging.<idx>.domain` here, but it's no big deal.

**Review by radeksimko — APPROVED** [review]
I left you one low-prio comment. If I understand correctly the API's behaviour regarding defaults has changed already, which already caused diffs to some people, so there's no point of adding any state migration. So if that's the case this LGTM.
