### PR TITLE
Keeping backends in directors when backends are modified

### LINKED ISSUE #143: Changing a weight can remove a backend from a director
### Terraform Version
0.11.13

### Affected Resource(s)
fastly_service_v1

### Terraform Configuration Files
I updated the weight from 99 to 9 in the file below:

```hcl
resource "fastly_service_v1" "fastly_service" {
  name = "${var.fastly_project_name}"

  domain {
    name = "${var.domain_name}"
  }

  backend ="${var.backends}" 

  // To fix the issue https://github.com/terraform-providers/terraform-provider-fastly/issues/109,
  // we only put the backends with weight greater than 0 in the director.
  director {
    name = "director"
    backends = [ "${compact(data.null_data_source.non_zero_weight_backends.*.outputs.name)}"]
    quorum = 1
  }
}
data "null_data_source" "non_zero_weight_backends" {
  count = "${length(var.backends)}"
  inputs = {
    name = "${lookup(var.backends[count.index], "weight") == 0 ? "" : lookup(var.backends[count.index], "name")}"
  }
}
```
```
backends = [
    {
      name = "xxxxx Public API (xxxxx)"
      address = xxxxx
      port = 443
      ssl_cert_hostname = xxxxx
      ssl_check_cert = true
      use_ssl = true
      min_tls_version = "1.2"

      weight = 9
    },
    {
      name = "xxxx Public API"
      address = xxxxx
      port = 443
      ssl_cert_hostname = xxxxx
      ssl_check_cert = true
      use_ssl = true
      min_tls_version = "1.2"

      weight = 1
    }
  ]
```

### Debug Output
```
  backend.205921849.address:                "xxxx"
  backend.205921849.auto_loadbalance:       "true" => "true"
  backend.205921849.between_bytes_timeout:  "10000" => "10000"
  backend.205921849.connect_timeout:        "1000" => "1000"
  backend.205921849.error_threshold:        "0" => "0"
  backend.205921849.first_byte_timeout:     "15000" => "15000"
  backend.205921849.healthcheck:            "" => ""
  backend.205921849.max_conn:               "200" => "200"
  backend.205921849.max_tls_version:        "" => ""
  backend.205921849.min_tls_version:        "1.2" => "1.2"
  backend.205921849.name:                   "xxx"
  backend.205921849.port:                   "443" => "443"
  backend.205921849.request_condition:      "" => ""
  backend.205921849.shield:                 "" => ""
  backend.205921849.ssl_ca_cert:            "" => ""
  backend.205921849.ssl_cert_hostname:      "xxx"
  backend.205921849.ssl_check_cert:         "true" => "true"
  backend.205921849.ssl_ciphers:            "" => ""
  backend.205921849.ssl_client_cert:        "<sensitive>" => "<sensitive>"
  backend.205921849.ssl_client_key:         "<sensitive>" => "<sensitive>"
  backend.205921849.ssl_hostname:           "" => ""
  backend.205921849.ssl_sni_hostname:       "" => ""
  backend.205921849.use_ssl:                "true" => "true"
  backend.205921849.weight:                 "1" => "1"
  backend.2547690010.address:               "" => "xxxx"
  backend.2547690010.auto_loadbalance:      "" => "true"
  backend.2547690010.between_bytes_timeout: "" => "10000"
  backend.2547690010.connect_timeout:       "" => "1000"
  backend.2547690010.error_threshold:       "" => "0"
  backend.2547690010.first_byte_timeout:    "" => "15000"
  backend.2547690010.healthcheck:           "" => ""
  backend.2547690010.max_conn:              "" => "200"
  backend.2547690010.max_tls_version:       "" => ""
  backend.2547690010.min_tls_version:       "" => "1.2"
  backend.2547690010.name:                  "" => "xxxx"
  backend.2547690010.port:                  "" => "443"
  backend.2547690010.request_condition:     "" => ""
  backend.2547690010.shield:                "" => ""
  backend.2547690010.ssl_ca_cert:           "" => ""
  backend.2547690010.ssl_cert_hostname:     "" => "xxxx"
  backend.2547690010.ssl_check_cert:        "" => "true"
  backend.2547690010.ssl_ciphers:           "" => ""
  backend.2547690010.ssl_client_cert:       "<sensitive>" => "<sensitive>"
  backend.2547690010.ssl_client_key:        "<sensitive>" => "<sensitive>"
  backend.2547690010.ssl_hostname:          "" => ""
  backend.2547690010.ssl_sni_hostname:      "" => ""
  backend.2547690010.use_ssl:               "" => "true"
  backend.2547690010.weight:                "" => "9"
  backend.2898937851.address:               "xxx" => ""
  backend.2898937851.auto_loadbalance:      "true" => "false"
  backend.2898937851.between_bytes_timeout: "10000" => "0"
  backend.2898937851.connect_timeout:       "1000" => "0"
  backend.2898937851.error_threshold:       "0" => "0"
  backend.2898937851.first_byte_timeout:    "15000" => "0"
  backend.2898937851.healthcheck:           "" => ""
  backend.2898937851.max_conn:              "200" => "0"
  backend.2898937851.max_tls_version:       "" => ""
  backend.2898937851.min_tls_version:       "1.2" => ""
  backend.2898937851.name:                  "xxx" => ""
  backend.2898937851.port:                  "443" => "0"
  backend.2898937851.request_condition:     "" => ""
  backend.2898937851.shield:                "" => ""
  backend.2898937851.ssl_ca_cert:           "" => ""
  backend.2898937851.ssl_cert_hostname:     "xxxx" => ""
  backend.2898937851.ssl_check_cert:        "true" => "false"
  backend.2898937851.ssl_ciphers:           "" => ""
  backend.2898937851.ssl_client_cert:       "" => ""
  backend.2898937851.ssl_client_key:        "" => ""
  backend.2898937851.ssl_hostname:          "" => ""
  backend.2898937851.ssl_sni_hostname:      "" => ""
  backend.2898937851.use_ssl:               "true" => "false"
  backend.2898937851.weight:                "99" => "0"
```
### Expected Behavior
The director should update the weight in the VCL

### Actual Behavior
The API removed the backend with the updated weight from the director.

### Steps to Reproduce
1. Updated the weight on one backend
2. `terraform apply`

### Important Factoids
Running apply again fixes the issue with the plan:
```
  director.1777961031.backends.#:          "0" => "2"
  director.1777961031.backends.3220782306: "" => "xxxx"
  director.1777961031.backends.3231695452: "" => "xxxx"
  director.1777961031.capacity:            "" => "100"
  director.1777961031.comment:             "" => ""
  director.1777961031.name:                "" => "director"
  director.1777961031.quorum:              "" => "1"
  director.1777961031.retries:             "" => "5"
  director.1777961031.shield:              "" => ""
  director.1777961031.type:                "" => "1"
  director.2719870166.backends.#:          "1" => "0"
  director.2719870166.backends.3220782306: "xxxxI" => ""
  director.2719870166.capacity:            "100" => "0"
  director.2719870166.comment:             "" => ""
  director.2719870166.name:                "director" => ""
  director.2719870166.quorum:              "1" => "0"
  director.2719870166.retries:             "5" => "0"
  director.2719870166.shield:              "" => ""
  director.2719870166.type:                "1" => "0"
```

### PR DESCRIPTION
**Pull request by matpimenta**
Fixes #143 

This change is based on the Option 2 described on #197 and some further analysis to determine the best option.

I've made the Diff computation a separate component so that in the future, other parts of the code can re-use it to perform updates instead of delete/create.

I've also fixed some unrelated issues with logging endpoints on the compute resource (see commit cc7bec3) which was causing the acceptance tests to fail.

<details><summary>Acceptance Test results</summary>
<p>

```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v  -timeout 360m -ldflags="-X=github.com/fastly/terraform-provider-fastly/version.ProviderVersion=acc"
?       github.com/terraform-providers/terraform-provider-fastly        [no test files]
=== RUN   TestResourceFastlyFlattenAcl
--- PASS: TestResourceFastlyFlattenAcl (0.00s)
=== RUN   TestAccFastlyServiceV1_acl
--- PASS: TestAccFastlyServiceV1_acl (76.48s)
=== RUN   TestAccFastlyServiceV1_bigquerylogging
--- PASS: TestAccFastlyServiceV1_bigquerylogging (70.51s)
=== RUN   TestAccFastlyServiceV1_bigquerylogging_compute
--- PASS: TestAccFastlyServiceV1_bigquerylogging_compute (58.07s)
=== RUN   TestAccFastlyServiceV1_bigquerylogging_env
--- PASS: TestAccFastlyServiceV1_bigquerylogging_env (70.25s)
=== RUN   TestResourceFastlyFlattenBigQuery
--- PASS: TestResourceFastlyFlattenBigQuery (0.18s)
=== RUN   TestResourceFastlyFlattenBlobStorage
--- PASS: TestResourceFastlyFlattenBlobStorage (0.00s)
=== RUN   TestAccFastlyServiceV1_blobstoragelogging_basic
--- PASS: TestAccFastlyServiceV1_blobstoragelogging_basic (131.49s)
=== RUN   TestAccFastlyServiceV1_blobstoragelogging_basic_compute
--- PASS: TestAccFastlyServiceV1_blobstoragelogging_basic_compute (51.44s)
=== RUN   TestAccFastlyServiceV1_blobstoragelogging_default
--- PASS: TestAccFastlyServiceV1_blobstoragelogging_default (63.51s)
=== RUN   TestAccFastlyServiceV1_blobstoragelogging_env
--- PASS: TestAccFastlyServiceV1_blobstoragelogging_env (59.11s)
=== RUN   TestResourceFastlyFlattenCacheSettings
--- PASS: TestResourceFastlyFlattenCacheSettings (0.00s)
=== RUN   TestAccFastlyServiceV1CacheSetting_basic
--- PASS: TestAccFastlyServiceV1CacheSetting_basic (123.27s)
=== RUN   TestResourceFastlyFlattenConditions
--- PASS: TestResourceFastlyFlattenConditions (0.00s)
=== RUN   TestAccFastlyServiceV1_conditional_basic
--- PASS: TestAccFastlyServiceV1_conditional_basic (59.27s)
=== RUN   TestResourceFastlyFlattenDictionary
--- PASS: TestResourceFastlyFlattenDictionary (0.00s)
=== RUN   TestAccFastlyServiceV1_dictionary
--- PASS: TestAccFastlyServiceV1_dictionary (62.26s)
=== RUN   TestAccFastlyServiceV1_dictionary_write_only
--- PASS: TestAccFastlyServiceV1_dictionary_write_only (59.21s)
=== RUN   TestAccFastlyServiceV1_dictionary_update_name
--- PASS: TestAccFastlyServiceV1_dictionary_update_name (122.33s)
=== RUN   TestAccFastlyServiceV1_dictionary_update_write_only
--- PASS: TestAccFastlyServiceV1_dictionary_update_write_only (125.92s)
=== RUN   TestResourceFastlyFlattenDirectors
--- PASS: TestResourceFastlyFlattenDirectors (0.00s)
=== RUN   TestAccFastlyServiceV1_directors_basic
--- PASS: TestAccFastlyServiceV1_directors_basic (145.08s)
=== RUN   TestResourceFastlyFlattenDynamicSnippets
--- PASS: TestResourceFastlyFlattenDynamicSnippets (0.00s)
=== RUN   TestAccFastlyServiceV1DynamicSnippet_basic
--- PASS: TestAccFastlyServiceV1DynamicSnippet_basic (119.39s)
=== RUN   TestResourceFastlyFlattenGCS
--- PASS: TestResourceFastlyFlattenGCS (0.18s)
=== RUN   TestAccFastlyServiceV1_gcslogging
--- PASS: TestAccFastlyServiceV1_gcslogging (61.71s)
=== RUN   TestAccFastlyServiceV1_gcslogging_compute
--- PASS: TestAccFastlyServiceV1_gcslogging_compute (49.15s)
=== RUN   TestAccFastlyServiceV1_gcslogging_env
--- PASS: TestAccFastlyServiceV1_gcslogging_env (58.64s)
=== RUN   TestResourceFastlyFlattenGzips
--- PASS: TestResourceFastlyFlattenGzips (0.00s)
=== RUN   TestAccFastlyServiceV1_gzips_basic
--- PASS: TestAccFastlyServiceV1_gzips_basic (124.41s)
=== RUN   TestResourceFastlyFlattenHeaders
--- PASS: TestResourceFastlyFlattenHeaders (0.00s)
=== RUN   TestFastlyServiceV1_BuildHeaders
--- PASS: TestFastlyServiceV1_BuildHeaders (0.00s)
=== RUN   TestAccFastlyServiceV1_headers_basic
--- PASS: TestAccFastlyServiceV1_headers_basic (156.23s)
=== RUN   TestResourceFastlyFlattenHealthChecks
--- PASS: TestResourceFastlyFlattenHealthChecks (0.00s)
=== RUN   TestAccFastlyServiceV1_healthcheck_basic
--- PASS: TestAccFastlyServiceV1_healthcheck_basic (118.75s)
=== RUN   TestResourceFastlyFlattenHTTPS
--- PASS: TestResourceFastlyFlattenHTTPS (0.00s)
=== RUN   TestAccFastlyServiceV1_httpslogging_basic
--- PASS: TestAccFastlyServiceV1_httpslogging_basic (133.28s)
=== RUN   TestAccFastlyServiceV1_httpslogging_basic_compute
--- PASS: TestAccFastlyServiceV1_httpslogging_basic_compute (50.33s)
=== RUN   TestResourceFastlyFlattenLogentries
--- PASS: TestResourceFastlyFlattenLogentries (0.00s)
=== RUN   TestAccFastlyServiceV1_logentries_basic
--- PASS: TestAccFastlyServiceV1_logentries_basic (123.60s)
=== RUN   TestAccFastlyServiceV1_logentries_basic_compute
--- PASS: TestAccFastlyServiceV1_logentries_basic_compute (48.85s)
=== RUN   TestAccFastlyServiceV1_logentries_formatVersion
--- PASS: TestAccFastlyServiceV1_logentries_formatVersion (62.31s)
=== RUN   TestResourceFastlyFlattenCloudfiles
--- PASS: TestResourceFastlyFlattenCloudfiles (0.00s)
=== RUN   TestAccFastlyServiceV1_logging_cloudfiles_basic
--- PASS: TestAccFastlyServiceV1_logging_cloudfiles_basic (121.86s)
=== RUN   TestAccFastlyServiceV1_logging_cloudfiles_basic_compute
--- PASS: TestAccFastlyServiceV1_logging_cloudfiles_basic_compute (50.49s)
=== RUN   TestResourceFastlyFlattenDatadog
--- PASS: TestResourceFastlyFlattenDatadog (0.00s)
=== RUN   TestAccFastlyServiceV1_logging_datadog_basic
--- PASS: TestAccFastlyServiceV1_logging_datadog_basic (127.03s)
=== RUN   TestAccFastlyServiceV1_logging_datadog_basic_compute
--- PASS: TestAccFastlyServiceV1_logging_datadog_basic_compute (50.76s)
=== RUN   TestResourceFastlyFlattenDigitalOcean
--- PASS: TestResourceFastlyFlattenDigitalOcean (0.01s)
=== RUN   TestAccFastlyServiceV1_logging_digitalocean_basic
--- PASS: TestAccFastlyServiceV1_logging_digitalocean_basic (122.81s)
=== RUN   TestAccFastlyServiceV1_logging_digitalocean_basic_compute
--- PASS: TestAccFastlyServiceV1_logging_digitalocean_basic_compute (51.36s)
=== RUN   TestResourceFastlyFlattenElasticsearch
--- PASS: TestResourceFastlyFlattenElasticsearch (0.01s)
=== RUN   TestAccFastlyServiceV1_logging_elasticsearch_basic
--- PASS: TestAccFastlyServiceV1_logging_elasticsearch_basic (138.44s)
=== RUN   TestAccFastlyServiceV1_logging_elasticsearch_basic_compute
--- PASS: TestAccFastlyServiceV1_logging_elasticsearch_basic_compute (55.35s)
=== RUN   TestResourceFastlyFlattenFTP
--- PASS: TestResourceFastlyFlattenFTP (0.00s)
=== RUN   TestAccFastlyServiceV1_logging_ftp_basic
--- PASS: TestAccFastlyServiceV1_logging_ftp_basic (129.00s)
=== RUN   TestAccFastlyServiceV1_logging_ftp_basic_compute
--- PASS: TestAccFastlyServiceV1_logging_ftp_basic_compute (54.25s)
=== RUN   TestResourceFastlyFlattenGooglePubSub
--- PASS: TestResourceFastlyFlattenGooglePubSub (0.00s)
=== RUN   TestAccFastlyServiceV1_googlepubsublogging_basic
--- PASS: TestAccFastlyServiceV1_googlepubsublogging_basic (124.06s)
=== RUN   TestAccFastlyServiceV1_googlepubsublogging_basic_compute
--- PASS: TestAccFastlyServiceV1_googlepubsublogging_basic_compute (50.28s)
=== RUN   TestResourceFastlyFlattenHeroku
--- PASS: TestResourceFastlyFlattenHeroku (0.00s)
=== RUN   TestAccFastlyServiceV1_logging_heroku_basic
--- PASS: TestAccFastlyServiceV1_logging_heroku_basic (124.44s)
=== RUN   TestAccFastlyServiceV1_logging_heroku_basic_compute
--- PASS: TestAccFastlyServiceV1_logging_heroku_basic_compute (52.66s)
=== RUN   TestResourceFastlyFlattenHoneycomb
--- PASS: TestResourceFastlyFlattenHoneycomb (0.00s)
=== RUN   TestAccFastlyServiceV1_logging_honeycomb_basic
--- PASS: TestAccFastlyServiceV1_logging_honeycomb_basic (124.08s)
=== RUN   TestAccFastlyServiceV1_logging_honeycomb_basic_compute
--- PASS: TestAccFastlyServiceV1_logging_honeycomb_basic_compute (49.19s)
=== RUN   TestResourceFastlyFlattenKafka
--- PASS: TestResourceFastlyFlattenKafka (0.00s)
=== RUN   TestAccFastlyServiceV1_kafkalogging_basic
--- PASS: TestAccFastlyServiceV1_kafkalogging_basic (126.13s)
=== RUN   TestAccFastlyServiceV1_kafkalogging_basic_compute
--- PASS: TestAccFastlyServiceV1_kafkalogging_basic_compute (50.67s)
=== RUN   TestResourceFastlyFlattenLoggly
--- PASS: TestResourceFastlyFlattenLoggly (0.00s)
=== RUN   TestAccFastlyServiceV1_logging_loggly_basic
--- PASS: TestAccFastlyServiceV1_logging_loggly_basic (120.99s)
=== RUN   TestAccFastlyServiceV1_logging_loggly_basic_compute
--- PASS: TestAccFastlyServiceV1_logging_loggly_basic_compute (51.47s)
=== RUN   TestResourceFastlyFlattenLogshuttle
--- PASS: TestResourceFastlyFlattenLogshuttle (0.00s)
=== RUN   TestAccFastlyServiceV1_logging_logshuttle_basic
--- PASS: TestAccFastlyServiceV1_logging_logshuttle_basic (119.91s)
=== RUN   TestAccFastlyServiceV1_logging_logshuttle_basic_compute
--- PASS: TestAccFastlyServiceV1_logging_logshuttle_basic_compute (50.74s)
=== RUN   TestResourceFastlyFlattenNewRelic
--- PASS: TestResourceFastlyFlattenNewRelic (0.00s)
=== RUN   TestAccFastlyServiceV1_logging_newrelic_basic
--- PASS: TestAccFastlyServiceV1_logging_newrelic_basic (123.52s)
=== RUN   TestAccFastlyServiceV1_logging_newrelic_basic_compute
--- PASS: TestAccFastlyServiceV1_logging_newrelic_basic_compute (48.01s)
=== RUN   TestResourceFastlyFlattenOpenstack
--- PASS: TestResourceFastlyFlattenOpenstack (0.01s)
=== RUN   TestAccFastlyServiceV1_logging_openstack_basic
--- PASS: TestAccFastlyServiceV1_logging_openstack_basic (125.66s)
=== RUN   TestAccFastlyServiceV1_logging_openstack_basic_compute
--- PASS: TestAccFastlyServiceV1_logging_openstack_basic_compute (48.03s)
=== RUN   TestResourceFastlyFlattenScalyr
--- PASS: TestResourceFastlyFlattenScalyr (0.00s)
=== RUN   TestAccFastlyServiceV1_scalyrlogging_basic
--- PASS: TestAccFastlyServiceV1_scalyrlogging_basic (125.18s)
=== RUN   TestAccFastlyServiceV1_scalyrlogging_basic_compute
--- PASS: TestAccFastlyServiceV1_scalyrlogging_basic_compute (48.48s)
=== RUN   TestResourceFastlyFlattenSFTP
--- PASS: TestResourceFastlyFlattenSFTP (0.00s)
=== RUN   TestAccFastlyServiceV1_logging_sftp_basic
--- PASS: TestAccFastlyServiceV1_logging_sftp_basic (123.24s)
=== RUN   TestAccFastlyServiceV1_logging_sftp_basic_compute
--- PASS: TestAccFastlyServiceV1_logging_sftp_basic_compute (48.13s)
=== RUN   TestAccFastlyServiceV1_logging_sftp_password_secret_key
--- PASS: TestAccFastlyServiceV1_logging_sftp_password_secret_key (4.52s)
=== RUN   TestAccFastlyServiceV1_package_basic
--- PASS: TestAccFastlyServiceV1_package_basic (158.93s)
=== RUN   TestResourceFastlyFlattenPapertrail
--- PASS: TestResourceFastlyFlattenPapertrail (0.00s)
=== RUN   TestAccFastlyServiceV1_papertrail_basic
--- PASS: TestAccFastlyServiceV1_papertrail_basic (118.77s)
=== RUN   TestAccFastlyServiceV1_papertrail_basic_compute
--- PASS: TestAccFastlyServiceV1_papertrail_basic_compute (50.13s)
=== RUN   TestResourceFastlyFlattenRequestSettings
--- PASS: TestResourceFastlyFlattenRequestSettings (0.00s)
=== RUN   TestAccFastlyServiceV1RequestSetting_basic
--- PASS: TestAccFastlyServiceV1RequestSetting_basic (58.72s)
=== RUN   TestResourceFastlyFlattenResponseObjects
--- PASS: TestResourceFastlyFlattenResponseObjects (0.00s)
=== RUN   TestAccFastlyServiceV1_response_object_basic
--- PASS: TestAccFastlyServiceV1_response_object_basic (121.55s)
=== RUN   TestResourceFastlyFlattenS3
--- PASS: TestResourceFastlyFlattenS3 (0.00s)
=== RUN   TestAccFastlyServiceV1_s3logging_basic
--- PASS: TestAccFastlyServiceV1_s3logging_basic (134.01s)
=== RUN   TestAccFastlyServiceV1_s3logging_basic_compute
--- PASS: TestAccFastlyServiceV1_s3logging_basic_compute (48.18s)
=== RUN   TestAccFastlyServiceV1_s3logging_domain_default
--- PASS: TestAccFastlyServiceV1_s3logging_domain_default (59.59s)
=== RUN   TestAccFastlyServiceV1_s3logging_s3_env
--- PASS: TestAccFastlyServiceV1_s3logging_s3_env (57.82s)
=== RUN   TestAccFastlyServiceV1_s3logging_formatVersion
--- PASS: TestAccFastlyServiceV1_s3logging_formatVersion (58.63s)
=== RUN   TestResourceFastlyFlattenSnippets
--- PASS: TestResourceFastlyFlattenSnippets (0.00s)
=== RUN   TestAccFastlyServiceV1Snippet_basic
--- PASS: TestAccFastlyServiceV1Snippet_basic (120.47s)
=== RUN   TestResourceFastlyFlattenSplunk
--- PASS: TestResourceFastlyFlattenSplunk (0.25s)
=== RUN   TestAccFastlyServiceV1_splunk_basic
--- PASS: TestAccFastlyServiceV1_splunk_basic (122.65s)
=== RUN   TestAccFastlyServiceV1_splunk_basic_compute
--- PASS: TestAccFastlyServiceV1_splunk_basic_compute (49.70s)
=== RUN   TestAccFastlyServiceV1_splunk_default
--- PASS: TestAccFastlyServiceV1_splunk_default (58.47s)
=== RUN   TestAccFastlyServiceV1_splunk_complete
--- PASS: TestAccFastlyServiceV1_splunk_complete (125.91s)
=== RUN   TestAccFastlyServiceV1_splunk_env
--- PASS: TestAccFastlyServiceV1_splunk_env (60.03s)
=== RUN   TestResourceFastlyFlattenSumologic
--- PASS: TestResourceFastlyFlattenSumologic (0.00s)
=== RUN   TestAccFastlyServiceV1_sumologic
--- PASS: TestAccFastlyServiceV1_sumologic (147.03s)
=== RUN   TestAccFastlyServiceV1_sumologic_compute
--- PASS: TestAccFastlyServiceV1_sumologic_compute (48.34s)
=== RUN   TestResourceFastlyFlattenSyslog
--- PASS: TestResourceFastlyFlattenSyslog (0.60s)
=== RUN   TestAccFastlyServiceV1_syslog_basic
--- PASS: TestAccFastlyServiceV1_syslog_basic (128.68s)
=== RUN   TestAccFastlyServiceV1_syslog_basic_compute
--- PASS: TestAccFastlyServiceV1_syslog_basic_compute (50.44s)
=== RUN   TestAccFastlyServiceV1_syslog_formatVersion
--- PASS: TestAccFastlyServiceV1_syslog_formatVersion (60.54s)
=== RUN   TestAccFastlyServiceV1_syslog_useTls
--- PASS: TestAccFastlyServiceV1_syslog_useTls (58.35s)
=== RUN   TestResourceFastlyFlattenVCLs
--- PASS: TestResourceFastlyFlattenVCLs (0.00s)
=== RUN   TestAccFastlyServiceV1_VCL_basic
--- PASS: TestAccFastlyServiceV1_VCL_basic (128.82s)
=== RUN   TestResourceFastlyFlattenWAF
--- PASS: TestResourceFastlyFlattenWAF (0.00s)
=== RUN   TestAccFastlyServiceV1WAFAdd
=== PAUSE TestAccFastlyServiceV1WAFAdd
=== RUN   TestAccFastlyServiceV1WAFAddAndRemove
=== PAUSE TestAccFastlyServiceV1WAFAddAndRemove
=== RUN   TestAccFastlyServiceV1WAFUpdateResponse
=== PAUSE TestAccFastlyServiceV1WAFUpdateResponse
=== RUN   TestAccFastlyServiceV1WAFUpdateCondition
=== PAUSE TestAccFastlyServiceV1WAFUpdateCondition
=== RUN   TestAccFastlyServiceWAFVersionV1FlattenWAFActiveRules
--- PASS: TestAccFastlyServiceWAFVersionV1FlattenWAFActiveRules (0.00s)
=== RUN   TestAccFastlyServiceWAFVersionV1FlattenWAFDeleteByModSecID
--- PASS: TestAccFastlyServiceWAFVersionV1FlattenWAFDeleteByModSecID (0.00s)
=== RUN   TestAccFastlyServiceWAFVersionV1AddWithRules
=== PAUSE TestAccFastlyServiceWAFVersionV1AddWithRules
=== RUN   TestAccFastlyServiceWAFVersionV1UpdateRules
=== PAUSE TestAccFastlyServiceWAFVersionV1UpdateRules
=== RUN   TestAccFastlyServiceWAFVersionV1DeleteRules
=== PAUSE TestAccFastlyServiceWAFVersionV1DeleteRules
=== RUN   TestAccFastlyServiceWAFVersionV1ImportWithRules
--- PASS: TestAccFastlyServiceWAFVersionV1ImportWithRules (121.30s)
=== RUN   TestUserAgentContainsProviderVersion
--- PASS: TestUserAgentContainsProviderVersion (0.00s)
=== RUN   TestStringPtr
--- PASS: TestStringPtr (0.00s)
=== RUN   TestIntPtr
--- PASS: TestIntPtr (0.00s)
=== RUN   TestBoolPtr
--- PASS: TestBoolPtr (0.00s)
=== RUN   TestDefaultUintToZero
--- PASS: TestDefaultUintToZero (0.00s)
=== RUN   TestDefaultUint
--- PASS: TestDefaultUint (0.00s)
=== RUN   TestAccFastlyIPRanges
--- PASS: TestAccFastlyIPRanges (1.12s)
=== RUN   TestAccFastlyWAFRulesDetermineRevision
--- PASS: TestAccFastlyWAFRulesDetermineRevision (0.00s)
=== RUN   TestAccFastlyWAFRulesFlattenWAFRules
--- PASS: TestAccFastlyWAFRulesFlattenWAFRules (0.00s)
=== RUN   TestAccFastlyWAFRulesPublisherFilter
--- PASS: TestAccFastlyWAFRulesPublisherFilter (9.84s)
=== RUN   TestAccFastlyWAFRulesExcludeFilter
--- PASS: TestAccFastlyWAFRulesExcludeFilter (4.70s)
=== RUN   TestAccFastlyWAFRulesTagFilter
--- PASS: TestAccFastlyWAFRulesTagFilter (3.09s)
=== RUN   TestSetDiff_Diff
=== RUN   TestSetDiff_Diff/should_return_the_correct_diff
=== RUN   TestSetDiff_Diff/should_diff_empty_element_lists
=== RUN   TestSetDiff_Diff/should_return_error_if_key_cannot_be_computed
--- PASS: TestSetDiff_Diff (0.00s)
    --- PASS: TestSetDiff_Diff/should_return_the_correct_diff (0.00s)
    --- PASS: TestSetDiff_Diff/should_diff_empty_element_lists (0.00s)
    --- PASS: TestSetDiff_Diff/should_return_error_if_key_cannot_be_computed (0.00s)
=== RUN   TestEscapePercentSign
=== RUN   TestEscapePercentSign/string_no_percent_signs_should_change_nothing
=== RUN   TestEscapePercentSign/one_percent_sign_should_return_two_percent_signs
=== RUN   TestEscapePercentSign/one_percent_sign_mid-string_should_return_two_percent_signs_in_the_same_place
=== RUN   TestEscapePercentSign/one_percent_sign_before_left_curly_brace_should_return_four_percent_signs_then_curly_brace
--- PASS: TestEscapePercentSign (0.00s)
    --- PASS: TestEscapePercentSign/string_no_percent_signs_should_change_nothing (0.00s)
    --- PASS: TestEscapePercentSign/one_percent_sign_should_return_two_percent_signs (0.00s)
    --- PASS: TestEscapePercentSign/one_percent_sign_mid-string_should_return_two_percent_signs_in_the_same_place (0.00s)
    --- PASS: TestEscapePercentSign/one_percent_sign_before_left_curly_brace_should_return_four_percent_signs_then_curly_brace (0.00s)
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestResourceFastlyFlattenAclEntries
--- PASS: TestResourceFastlyFlattenAclEntries (0.00s)
=== RUN   TestAccFastlyServiceAclEntriesV1_create
--- PASS: TestAccFastlyServiceAclEntriesV1_create (62.44s)
=== RUN   TestAccFastlyServiceAclEntriesV1_update
--- PASS: TestAccFastlyServiceAclEntriesV1_update (128.84s)
=== RUN   TestAccFastlyServiceAclEntriesV1_update_additional_fields
--- PASS: TestAccFastlyServiceAclEntriesV1_update_additional_fields (129.73s)
=== RUN   TestAccFastlyServiceAclEntriesV1_delete
--- PASS: TestAccFastlyServiceAclEntriesV1_delete (125.34s)
=== RUN   TestAccFastlyServiceAclEntriesV1_import
--- PASS: TestAccFastlyServiceAclEntriesV1_import (63.15s)
=== RUN   TestAccFastlyServiceAclEntriesV1_process_1001_entries
--- PASS: TestAccFastlyServiceAclEntriesV1_process_1001_entries (114.74s)
=== RUN   TestResourceFastlyFlattenBackendCompute
--- PASS: TestResourceFastlyFlattenBackendCompute (0.00s)
=== RUN   TestAccFastlyServiceCompute_basic
--- PASS: TestAccFastlyServiceCompute_basic (12.30s)
=== RUN   TestAccFastlyServiceCompute_import
--- PASS: TestAccFastlyServiceCompute_import (23.49s)
=== RUN   TestResourceFastlyFlattenDictionaryItems
--- PASS: TestResourceFastlyFlattenDictionaryItems (0.00s)
=== RUN   TestAccFastlyServiceDictionaryItemV1_create
--- PASS: TestAccFastlyServiceDictionaryItemV1_create (71.88s)
=== RUN   TestAccFastlyServiceDictionaryItemV1_create_dynamic
--- PASS: TestAccFastlyServiceDictionaryItemV1_create_dynamic (63.61s)
=== RUN   TestAccFastlyServiceDictionaryItemV1_update
--- PASS: TestAccFastlyServiceDictionaryItemV1_update (127.32s)
=== RUN   TestAccFastlyServiceDictionaryItemV1_external_item_is_removed
--- PASS: TestAccFastlyServiceDictionaryItemV1_external_item_is_removed (100.41s)
=== RUN   TestAccFastlyServiceDictionaryItemV1_external_item_deleted
--- PASS: TestAccFastlyServiceDictionaryItemV1_external_item_deleted (126.42s)
=== RUN   TestAccFastlyServiceDictionaryItemV1_batch_1001_items
--- PASS: TestAccFastlyServiceDictionaryItemV1_batch_1001_items (93.96s)
=== RUN   TestAccFastlyServiceDictionaryItemV1_import
--- PASS: TestAccFastlyServiceDictionaryItemV1_import (62.26s)
=== RUN   TestAccFastlyServiceDynamicSnippetContentV1_create
--- PASS: TestAccFastlyServiceDynamicSnippetContentV1_create (60.70s)
=== RUN   TestAccFastlyServiceDynamicSnippetContentV1_update
--- PASS: TestAccFastlyServiceDynamicSnippetContentV1_update (128.86s)
=== RUN   TestAccFastlyServiceDynamicSnippetContentV1_external_snippet_is_removed
--- PASS: TestAccFastlyServiceDynamicSnippetContentV1_external_snippet_is_removed (130.00s)
=== RUN   TestAccFastlyServiceDynamicSnippetContentV1_normal_snippet_is_not_removed
--- PASS: TestAccFastlyServiceDynamicSnippetContentV1_normal_snippet_is_not_removed (122.12s)
=== RUN   TestAccFastlyServiceDynamicSnippetContentV1_import
--- PASS: TestAccFastlyServiceDynamicSnippetContentV1_import (64.67s)
=== RUN   TestResourceFastlyFlattenDomains
--- PASS: TestResourceFastlyFlattenDomains (0.00s)
=== RUN   TestResourceFastlyFlattenBackend
--- PASS: TestResourceFastlyFlattenBackend (0.00s)
=== RUN   TestAccFastlyServiceV1_updateDomain
--- PASS: TestAccFastlyServiceV1_updateDomain (119.04s)
=== RUN   TestAccFastlyServiceV1_updateBackend
--- PASS: TestAccFastlyServiceV1_updateBackend (134.10s)
=== RUN   TestAccFastlyServiceV1_updateInvalidBackend
--- PASS: TestAccFastlyServiceV1_updateInvalidBackend (61.56s)
=== RUN   TestAccFastlyServiceV1_basic
--- PASS: TestAccFastlyServiceV1_basic (119.59s)
=== RUN   TestAccFastlyServiceV1_disappears
--- PASS: TestAccFastlyServiceV1_disappears (24.06s)
=== RUN   TestAccFastlyServiceV1_defaultTTL
--- PASS: TestAccFastlyServiceV1_defaultTTL (192.78s)
=== RUN   TestAccFastlyServiceV1_createDefaultTTL
--- PASS: TestAccFastlyServiceV1_createDefaultTTL (58.17s)
=== RUN   TestAccFastlyServiceV1_createZeroDefaultTTL
--- PASS: TestAccFastlyServiceV1_createZeroDefaultTTL (56.94s)
=== RUN   TestAccFastlyServiceV1_import
--- PASS: TestAccFastlyServiceV1_import (93.77s)
=== RUN   TestAccFastlyServiceV1_creation_with_versionless_resources
--- PASS: TestAccFastlyServiceV1_creation_with_versionless_resources (67.72s)
=== RUN   TestAccFastlyServiceWAFVersionV1DetermineVersion
--- PASS: TestAccFastlyServiceWAFVersionV1DetermineVersion (0.00s)
=== RUN   TestAccFastlyServiceWAFVersionV1Add
=== PAUSE TestAccFastlyServiceWAFVersionV1Add
=== RUN   TestAccFastlyServiceWAFVersionV1AddExistingService
=== PAUSE TestAccFastlyServiceWAFVersionV1AddExistingService
=== RUN   TestAccFastlyServiceWAFVersionV1Update
=== PAUSE TestAccFastlyServiceWAFVersionV1Update
=== RUN   TestAccFastlyServiceWAFVersionV1Delete
=== PAUSE TestAccFastlyServiceWAFVersionV1Delete
=== RUN   TestAccFastlyServiceWAFVersionV1Import
--- PASS: TestAccFastlyServiceWAFVersionV1Import (152.84s)
=== RUN   TestAccFastlyUserV1_basic
--- PASS: TestAccFastlyUserV1_basic (4.88s)
=== RUN   TestAccFastlyUserV1_updateLogin
--- PASS: TestAccFastlyUserV1_updateLogin (4.61s)
=== RUN   TestAccFastlyServiceWAFVersionDeploymentStatus
=== RUN   TestAccFastlyServiceWAFVersionDeploymentStatus/Status_
=== RUN   TestAccFastlyServiceWAFVersionDeploymentStatus/Status_failed
=== RUN   TestAccFastlyServiceWAFVersionDeploymentStatus/Status_completed
--- PASS: TestAccFastlyServiceWAFVersionDeploymentStatus (0.40s)
    --- PASS: TestAccFastlyServiceWAFVersionDeploymentStatus/Status_ (0.00s)
    --- PASS: TestAccFastlyServiceWAFVersionDeploymentStatus/Status_failed (0.00s)
    --- PASS: TestAccFastlyServiceWAFVersionDeploymentStatus/Status_completed (0.40s)
=== RUN   TestValidateLoggingFormatVersion
=== RUN   TestValidateLoggingFormatVersion/0
=== RUN   TestValidateLoggingFormatVersion/1
=== RUN   TestValidateLoggingFormatVersion/2
=== RUN   TestValidateLoggingFormatVersion/3
=== RUN   TestValidateLoggingFormatVersion/4
=== RUN   TestValidateLoggingFormatVersion/5
--- PASS: TestValidateLoggingFormatVersion (0.00s)
    --- PASS: TestValidateLoggingFormatVersion/0 (0.00s)
    --- PASS: TestValidateLoggingFormatVersion/1 (0.00s)
    --- PASS: TestValidateLoggingFormatVersion/2 (0.00s)
    --- PASS: TestValidateLoggingFormatVersion/3 (0.00s)
    --- PASS: TestValidateLoggingFormatVersion/4 (0.00s)
    --- PASS: TestValidateLoggingFormatVersion/5 (0.00s)
=== RUN   TestValidateLoggingMessageType
=== RUN   TestValidateLoggingMessageType/classic
=== RUN   TestValidateLoggingMessageType/loggly
=== RUN   TestValidateLoggingMessageType/logplex
=== RUN   TestValidateLoggingMessageType/blank
=== RUN   TestValidateLoggingMessageType/CLASSIC
=== RUN   TestValidateLoggingMessageType/LOGGLY
=== RUN   TestValidateLoggingMessageType/LOGPLEX
=== RUN   TestValidateLoggingMessageType/BLANK
--- PASS: TestValidateLoggingMessageType (0.00s)
    --- PASS: TestValidateLoggingMessageType/classic (0.00s)
    --- PASS: TestValidateLoggingMessageType/loggly (0.00s)
    --- PASS: TestValidateLoggingMessageType/logplex (0.00s)
    --- PASS: TestValidateLoggingMessageType/blank (0.00s)
    --- PASS: TestValidateLoggingMessageType/CLASSIC (0.00s)
    --- PASS: TestValidateLoggingMessageType/LOGGLY (0.00s)
    --- PASS: TestValidateLoggingMessageType/LOGPLEX (0.00s)
    --- PASS: TestValidateLoggingMessageType/BLANK (0.00s)
=== RUN   TestValidateLoggingPlacement
=== RUN   TestValidateLoggingPlacement/none
=== RUN   TestValidateLoggingPlacement/waf_debug
=== RUN   TestValidateLoggingPlacement/NONE
=== RUN   TestValidateLoggingPlacement/WAF_DEBUG
--- PASS: TestValidateLoggingPlacement (0.00s)
    --- PASS: TestValidateLoggingPlacement/none (0.00s)
    --- PASS: TestValidateLoggingPlacement/waf_debug (0.00s)
    --- PASS: TestValidateLoggingPlacement/NONE (0.00s)
    --- PASS: TestValidateLoggingPlacement/WAF_DEBUG (0.00s)
=== RUN   TestValidateLoggingServerSideEncryption
=== RUN   TestValidateLoggingServerSideEncryption/AES256
=== RUN   TestValidateLoggingServerSideEncryption/aws:kms
=== RUN   TestValidateLoggingServerSideEncryption/aes256
=== RUN   TestValidateLoggingServerSideEncryption/AWS:KMS
=== RUN   TestValidateLoggingServerSideEncryption/aws:KMS
=== RUN   TestValidateLoggingServerSideEncryption/AWS:kms
--- PASS: TestValidateLoggingServerSideEncryption (0.00s)
    --- PASS: TestValidateLoggingServerSideEncryption/AES256 (0.00s)
    --- PASS: TestValidateLoggingServerSideEncryption/aws:kms (0.00s)
    --- PASS: TestValidateLoggingServerSideEncryption/aes256 (0.00s)
    --- PASS: TestValidateLoggingServerSideEncryption/AWS:KMS (0.00s)
    --- PASS: TestValidateLoggingServerSideEncryption/aws:KMS (0.00s)
    --- PASS: TestValidateLoggingServerSideEncryption/AWS:kms (0.00s)
=== RUN   TestValidateDirectorQuorum
=== RUN   TestValidateDirectorQuorum/150
=== RUN   TestValidateDirectorQuorum/0
=== RUN   TestValidateDirectorQuorum/55
=== RUN   TestValidateDirectorQuorum/100
=== RUN   TestValidateDirectorQuorum/-1
=== RUN   TestValidateDirectorQuorum/101
--- PASS: TestValidateDirectorQuorum (0.00s)
    --- PASS: TestValidateDirectorQuorum/150 (0.00s)
    --- PASS: TestValidateDirectorQuorum/0 (0.00s)
    --- PASS: TestValidateDirectorQuorum/55 (0.00s)
    --- PASS: TestValidateDirectorQuorum/100 (0.00s)
    --- PASS: TestValidateDirectorQuorum/-1 (0.00s)
    --- PASS: TestValidateDirectorQuorum/101 (0.00s)
=== RUN   TestValidateDirectorType
=== RUN   TestValidateDirectorType/1
=== RUN   TestValidateDirectorType/2
=== RUN   TestValidateDirectorType/3
=== RUN   TestValidateDirectorType/4
=== RUN   TestValidateDirectorType/5
=== RUN   TestValidateDirectorType/0
--- PASS: TestValidateDirectorType (0.00s)
    --- PASS: TestValidateDirectorType/1 (0.00s)
    --- PASS: TestValidateDirectorType/2 (0.00s)
    --- PASS: TestValidateDirectorType/3 (0.00s)
    --- PASS: TestValidateDirectorType/4 (0.00s)
    --- PASS: TestValidateDirectorType/5 (0.00s)
    --- PASS: TestValidateDirectorType/0 (0.00s)
=== RUN   TestValidateConditionType
=== RUN   TestValidateConditionType/REQUEST
=== RUN   TestValidateConditionType/RESPONSE
=== RUN   TestValidateConditionType/CACHE
=== RUN   TestValidateConditionType/PREFETCH
=== RUN   TestValidateConditionType/request
=== RUN   TestValidateConditionType/response
=== RUN   TestValidateConditionType/cache
=== RUN   TestValidateConditionType/prefetch
--- PASS: TestValidateConditionType (0.00s)
    --- PASS: TestValidateConditionType/REQUEST (0.00s)
    --- PASS: TestValidateConditionType/RESPONSE (0.00s)
    --- PASS: TestValidateConditionType/CACHE (0.00s)
    --- PASS: TestValidateConditionType/PREFETCH (0.00s)
    --- PASS: TestValidateConditionType/request (0.00s)
    --- PASS: TestValidateConditionType/response (0.00s)
    --- PASS: TestValidateConditionType/cache (0.00s)
    --- PASS: TestValidateConditionType/prefetch (0.00s)
=== RUN   TestValidateHeaderAction
=== RUN   TestValidateHeaderAction/set
=== RUN   TestValidateHeaderAction/append
=== RUN   TestValidateHeaderAction/delete
=== RUN   TestValidateHeaderAction/regex
=== RUN   TestValidateHeaderAction/regex_repeat
=== RUN   TestValidateHeaderAction/SET
=== RUN   TestValidateHeaderAction/APPEND
=== RUN   TestValidateHeaderAction/DELETE
=== RUN   TestValidateHeaderAction/REGEX
=== RUN   TestValidateHeaderAction/REGEX_REPEAT
--- PASS: TestValidateHeaderAction (0.00s)
    --- PASS: TestValidateHeaderAction/set (0.00s)
    --- PASS: TestValidateHeaderAction/append (0.00s)
    --- PASS: TestValidateHeaderAction/delete (0.00s)
    --- PASS: TestValidateHeaderAction/regex (0.00s)
    --- PASS: TestValidateHeaderAction/regex_repeat (0.00s)
    --- PASS: TestValidateHeaderAction/SET (0.00s)
    --- PASS: TestValidateHeaderAction/APPEND (0.00s)
    --- PASS: TestValidateHeaderAction/DELETE (0.00s)
    --- PASS: TestValidateHeaderAction/REGEX (0.00s)
    --- PASS: TestValidateHeaderAction/REGEX_REPEAT (0.00s)
=== RUN   TestValidateHeaderType
=== RUN   TestValidateHeaderType/request
=== RUN   TestValidateHeaderType/fetch
=== RUN   TestValidateHeaderType/cache
=== RUN   TestValidateHeaderType/response
=== RUN   TestValidateHeaderType/REQUEST
=== RUN   TestValidateHeaderType/FETCH
=== RUN   TestValidateHeaderType/CACHE
=== RUN   TestValidateHeaderType/RESPONSE
--- PASS: TestValidateHeaderType (0.00s)
    --- PASS: TestValidateHeaderType/request (0.00s)
    --- PASS: TestValidateHeaderType/fetch (0.00s)
    --- PASS: TestValidateHeaderType/cache (0.00s)
    --- PASS: TestValidateHeaderType/response (0.00s)
    --- PASS: TestValidateHeaderType/REQUEST (0.00s)
    --- PASS: TestValidateHeaderType/FETCH (0.00s)
    --- PASS: TestValidateHeaderType/CACHE (0.00s)
    --- PASS: TestValidateHeaderType/RESPONSE (0.00s)
=== RUN   TestValidateRuleStatusType
=== RUN   TestValidateRuleStatusType/log
=== RUN   TestValidateRuleStatusType/block
=== RUN   TestValidateRuleStatusType/score
=== RUN   TestValidateRuleStatusType/123
=== RUN   TestValidateRuleStatusType/any
=== RUN   TestValidateRuleStatusType/???
--- PASS: TestValidateRuleStatusType (0.00s)
    --- PASS: TestValidateRuleStatusType/log (0.00s)
    --- PASS: TestValidateRuleStatusType/block (0.00s)
    --- PASS: TestValidateRuleStatusType/score (0.00s)
    --- PASS: TestValidateRuleStatusType/123 (0.00s)
    --- PASS: TestValidateRuleStatusType/any (0.00s)
    --- PASS: TestValidateRuleStatusType/??? (0.00s)
=== RUN   TestValidateSnippetType
=== RUN   TestValidateSnippetType/init
=== RUN   TestValidateSnippetType/recv
=== RUN   TestValidateSnippetType/hit
=== RUN   TestValidateSnippetType/miss
=== RUN   TestValidateSnippetType/pass
=== RUN   TestValidateSnippetType/hash
=== RUN   TestValidateSnippetType/fetch
=== RUN   TestValidateSnippetType/error
=== RUN   TestValidateSnippetType/deliver
=== RUN   TestValidateSnippetType/log
=== RUN   TestValidateSnippetType/none
=== RUN   TestValidateSnippetType/INIT
=== RUN   TestValidateSnippetType/RECV
=== RUN   TestValidateSnippetType/HIT
=== RUN   TestValidateSnippetType/MISS
=== RUN   TestValidateSnippetType/PASS
=== RUN   TestValidateSnippetType/FETCH
=== RUN   TestValidateSnippetType/HASH
=== RUN   TestValidateSnippetType/ERROR
=== RUN   TestValidateSnippetType/DELIVER
=== RUN   TestValidateSnippetType/LOG
=== RUN   TestValidateSnippetType/NONE
--- PASS: TestValidateSnippetType (0.00s)
    --- PASS: TestValidateSnippetType/init (0.00s)
    --- PASS: TestValidateSnippetType/recv (0.00s)
    --- PASS: TestValidateSnippetType/hit (0.00s)
    --- PASS: TestValidateSnippetType/miss (0.00s)
    --- PASS: TestValidateSnippetType/pass (0.00s)
    --- PASS: TestValidateSnippetType/hash (0.00s)
    --- PASS: TestValidateSnippetType/fetch (0.00s)
    --- PASS: TestValidateSnippetType/error (0.00s)
    --- PASS: TestValidateSnippetType/deliver (0.00s)
    --- PASS: TestValidateSnippetType/log (0.00s)
    --- PASS: TestValidateSnippetType/none (0.00s)
    --- PASS: TestValidateSnippetType/INIT (0.00s)
    --- PASS: TestValidateSnippetType/RECV (0.00s)
    --- PASS: TestValidateSnippetType/HIT (0.00s)
    --- PASS: TestValidateSnippetType/MISS (0.00s)
    --- PASS: TestValidateSnippetType/PASS (0.00s)
    --- PASS: TestValidateSnippetType/FETCH (0.00s)
    --- PASS: TestValidateSnippetType/HASH (0.00s)
    --- PASS: TestValidateSnippetType/ERROR (0.00s)
    --- PASS: TestValidateSnippetType/DELIVER (0.00s)
    --- PASS: TestValidateSnippetType/LOG (0.00s)
    --- PASS: TestValidateSnippetType/NONE (0.00s)
=== RUN   TestValidateDictionaryItemMaxSize
=== RUN   TestValidateDictionaryItemMaxSize/Ten_hundred_dictionary_items
=== RUN   TestValidateDictionaryItemMaxSize/Ten_thousand_dictionary_items
=== RUN   TestValidateDictionaryItemMaxSize/Ten_thousand_and_one_dictionary_items
--- PASS: TestValidateDictionaryItemMaxSize (0.01s)
    --- PASS: TestValidateDictionaryItemMaxSize/Ten_hundred_dictionary_items (0.00s)
    --- PASS: TestValidateDictionaryItemMaxSize/Ten_thousand_dictionary_items (0.00s)
    --- PASS: TestValidateDictionaryItemMaxSize/Ten_thousand_and_one_dictionary_items (0.00s)
=== RUN   TestValidateUserRole
=== RUN   TestValidateUserRole/user
=== RUN   TestValidateUserRole/billing
=== RUN   TestValidateUserRole/engineer
=== RUN   TestValidateUserRole/superuser
=== RUN   TestValidateUserRole/USER
=== RUN   TestValidateUserRole/BILLING
=== RUN   TestValidateUserRole/ENGINEER
=== RUN   TestValidateUserRole/SUPERUSER
--- PASS: TestValidateUserRole (0.00s)
    --- PASS: TestValidateUserRole/user (0.00s)
    --- PASS: TestValidateUserRole/billing (0.00s)
    --- PASS: TestValidateUserRole/engineer (0.00s)
    --- PASS: TestValidateUserRole/superuser (0.00s)
    --- PASS: TestValidateUserRole/USER (0.00s)
    --- PASS: TestValidateUserRole/BILLING (0.00s)
    --- PASS: TestValidateUserRole/ENGINEER (0.00s)
    --- PASS: TestValidateUserRole/SUPERUSER (0.00s)
=== RUN   TestValidateHTTPSURL
=== RUN   TestValidateHTTPSURL/https://api.fastly.com
=== RUN   TestValidateHTTPSURL/http://example.com
--- PASS: TestValidateHTTPSURL (0.00s)
    --- PASS: TestValidateHTTPSURL/https://api.fastly.com (0.00s)
    --- PASS: TestValidateHTTPSURL/http://example.com (0.00s)
=== CONT  TestAccFastlyServiceV1WAFAdd
=== CONT  TestAccFastlyServiceWAFVersionV1DeleteRules
=== CONT  TestAccFastlyServiceWAFVersionV1Update
=== CONT  TestAccFastlyServiceWAFVersionV1AddExistingService
=== CONT  TestAccFastlyServiceV1WAFUpdateCondition
=== CONT  TestAccFastlyServiceWAFVersionV1UpdateRules
=== CONT  TestAccFastlyServiceWAFVersionV1AddWithRules
=== CONT  TestAccFastlyServiceWAFVersionV1Add
--- PASS: TestAccFastlyServiceV1WAFAdd (93.32s)
=== CONT  TestAccFastlyServiceV1WAFUpdateResponse
--- PASS: TestAccFastlyServiceWAFVersionV1Add (153.91s)
=== CONT  TestAccFastlyServiceV1WAFAddAndRemove
--- PASS: TestAccFastlyServiceV1WAFUpdateCondition (158.25s)
=== CONT  TestAccFastlyServiceWAFVersionV1Delete
--- PASS: TestAccFastlyServiceWAFVersionV1AddWithRules (158.74s)
--- PASS: TestAccFastlyServiceWAFVersionV1AddExistingService (219.49s)
--- PASS: TestAccFastlyServiceV1WAFUpdateResponse (128.49s)
--- PASS: TestAccFastlyServiceWAFVersionV1UpdateRules (262.54s)
--- PASS: TestAccFastlyServiceWAFVersionV1Update (264.74s)
--- PASS: TestAccFastlyServiceWAFVersionV1DeleteRules (265.82s)
--- PASS: TestAccFastlyServiceWAFVersionV1Delete (158.74s)
--- PASS: TestAccFastlyServiceV1WAFAddAndRemove (187.63s)
PASS
ok      github.com/terraform-providers/terraform-provider-fastly/fastly 10690.050s
?       github.com/terraform-providers/terraform-provider-fastly/scripts/website        [no test files]
?       github.com/terraform-providers/terraform-provider-fastly/version        [no test files]

```

</p>
</details>

### CODE REVIEW

File: fastly/base_fastly_service_v1.go [hunk 1]
```diff
@@ -74,7 +74,7 @@ func (h *DefaultServiceAttributeHandler) MustProcess(d *schema.ResourceData, ini
 
 type VCLLoggingAttributes struct {
 	format            string
-	formatVersion     uint
+	formatVersion     *uint
```
Comment (mccurdyc) [inline fastly/base_fastly_service_v1.go]: Isn't this a required attribute for VCL services?

File: fastly/block_fastly_service_v1_backend.go [hunk 2]
```diff
@@ -33,17 +33,21 @@ func (h *BackendServiceAttributeHandler) Process(d *schema.ResourceData, latestV
...
 	// DELETE old Backends
-	for _, bRaw := range removeBackends {
+	for _, bRaw := range diffResult.Deleted {
 		bf := bRaw.(map[string]interface{})
-		opts := gofastly.DeleteBackendInput{
-			Service: d.Id(),
-			Version: latestVersion,
-			Name:    bf["name"].(string),
-		}
+		opts := h.createDeleteBackendInput(d.Id(), latestVersion, bf)
```
Comment (mccurdyc) [inline fastly/block_fastly_service_v1_backend.go:50]: I like these factory methods.

File: fastly/block_fastly_service_v1_backend.go [hunk 3]
```diff
@@ -56,51 +60,113 @@ func (h *BackendServiceAttributeHandler) Process(d *schema.ResourceData, latestV
...
+			return err
 		}
+	}
+
+	// UPDATE existing backends
+	for _, dRaw := range diffResult.Modified {
+		df := dRaw.(map[string]interface{})
+		opts := h.buildUpdateBackendInput(d.Id(), latestVersion, df)
 
 		log.Printf("[DEBUG] Create Backend Opts: %#v", opts)
```
Comment (mccurdyc) [inline fastly/block_fastly_service_v1_backend.go]:
```suggestion
		log.Printf("[DEBUG] Update Backend Opts: %#v", opts)
```

File: fastly/convert.go [hunk 4]
```diff
@@ -14,3 +14,10 @@ func intToPtr(i int) *int {
 func boolToPtr(i bool) *bool {
 	return &i
 }
+
+func uintWithDefault(int *uint) uint {
```
Comment (mccurdyc) [inline fastly/convert.go]: nitpick: In my opinion, I think it reads better as `uintOrDefault`. When I see `...WithDefault` I usually think that the caller will specify the default.

Totally a nitpick cc @phamann for his thought.

File: fastly/block_fastly_service_v1_sumologic.go [hunk 5]
```diff
@@ -67,7 +67,7 @@ func (h *SumologicServiceAttributeHandler) Process(d *schema.ResourceData, lates
 			URL:               sf["url"].(string),
 			MessageType:       sf["message_type"].(string),
 			Format:            vla.format,
-			FormatVersion:     int(vla.formatVersion),
+			FormatVersion:     int(uintWithDefault(vla.formatVersion)),
```
Comment (mccurdyc) [inline fastly/block_fastly_service_v1_sumologic.go]: Just noting Sumologic uses `int` - https://github.com/fastly/go-fastly/blob/master/fastly/sumologic.go#L21

This has been documented internally as a breaking change TODO.

File: fastly/diff.go [hunk 6]
```diff
@@ -0,0 +1,110 @@
+package fastly
```
Comment (mccurdyc) [inline fastly/diff.go:1]: I'd love to see `fastly/diff.go` and `fastly/diff_test.go` added in a separate PR with just those changes and get those merged in separately first. That was this is thoroughly reviewed and not missed.

I think ideally, we introduce this change and update existing resources and don't touch the resources' tests and ensure that they all pass.

File: fastly/diff.go [hunk 7]
```diff
@@ -0,0 +1,110 @@
...
+	}
+
+	// Compute all added and modified elements using Terraform set comparison method.
+	var added, modified []interface{}
+	for _, newElem := range newSet.Difference(oldSet).List() {
+		key, err := h.computeKey(newElem)
+		if err != nil {
+			return nil, newElementKeyError(newElem, err)
+		}
+		if oldSetMap[key] != nil {
```
Comment (mccurdyc) [inline fastly/diff.go:69]: This to me looks like the core bit of logic. Basically, creating two maps and comparing to identify if the old set had elements, etc.

File: fastly/block_fastly_service_v1_director_test.go [hunk 8]
```diff
@@ -253,12 +276,24 @@ resource "fastly_service_v1" "foo" {
     name    = "origin old"
   }
 
+  backend {
```
Comment (mccurdyc) [inline fastly/block_fastly_service_v1_director_test.go:279]: I think I understand these tests.

1. You create a service with 2 backends, each associated with a separate director.
2. You update update the field `weight` on a backend and ensure that it is still associated with the original directory

**Review by mccurdyc — COMMENTED** [review]
This LGTM. I'd like @phamann to take a look.

Below are just suggestions, overall this change looks good to me.

I was a bit overwhelmed by the change to `formatVersion` to use the new helper. Was this necessary for this change? Could we pull that out into a separate branch so that this change is strictly focused on the backend/director update? The only other suggestion that I had was to pull the new `Diff` logic out into its own change and to update the existing codebase to use that new logic, so that if we could test it with existing resources and rollback separately, if necessary.

File: fastly/convert.go (hunk 4 above)
Comment (matpimenta) [reply fastly/convert.go]: :) I was actually between `or` and `with`, I ended up with `with` but happy to change it

File: fastly/base_fastly_service_v1.go (hunk 1 above)
Comment (matpimenta) [reply fastly/base_fastly_service_v1.go]: `VCLLoggingAttributes` in each logging endpoint is populated regardless of the service type like:
```
		var vla = h.getVCLLoggingAttributes(sf)
		opts := gofastly.CreateGCSInput{
			Service:           d.Id(),
			Version:           latestVersion,
			Name:              sf["name"].(string),
			User:              sf["email"].(string),
			Bucket:            sf["bucket_name"].(string),
			SecretKey:         sf["secret_key"].(string),
			Path:              sf["path"].(string),
			Period:            uint(sf["period"].(int)),
			GzipLevel:         uint8(sf["gzip_level"].(int)),
			TimestampFormat:   sf["timestamp_format"].(string),
			MessageType:       sf["message_type"].(string),
			Format:            vla.format,
			ResponseCondition: vla.responseCondition,
			Placement:         vla.placement,
		}

```

This simplifies the logic when creating the Input object requests as it removes the need to have an `if`. It can cause problems with the defaults (which this change fixes). 
It will probably be a larger refactoring if we want to change the implementation and my goal here to fix the regression to get the acceptance tests back to green.

File: fastly/diff.go [hunk 9]
```diff
@@ -0,0 +1,110 @@
...
+// This object compares sets using Terraform's schema.Set methods (e.g. Difference() and Intersection())
+// so that the same differences displayed to the user are honoured here.
+//
+// SetDiff however is able to tell if two elements from two distinct sets have the same key. This is useful to detect
+// that an element should be updated instead of recreated on the remote server.
+type SetDiff struct {
+	keyFunc KeyFunc
+}
+
+// NewSetDiff creates a new SetDiff with a provided KeyFunc
```
Comment (phamann) [inline fastly/diff.go]:
```suggestion
// NewSetDiff creates a new SetDiff with a provided KeyFunc.
```

File: fastly/diff.go [hunk 10]
```diff
@@ -0,0 +1,110 @@
...
+func NewSetDiff(keyFunc KeyFunc) *SetDiff {
+	return &SetDiff{
+		keyFunc: keyFunc,
+	}
+}
+
+// DiffResult diffs to Set objects and returns a DiffResult object containing the diffs.
+//
+// The DiffResult object will contain the element from newSet on the Modified field.
+func (h *SetDiff) Diff(oldSet, newSet *schema.Set) (*DiffResult, error) {
```
Comment (phamann) [inline fastly/diff.go]: The comment doesn't match the function name and should have thrown a lint error. So we should either rename the function to `DiffResult` or update the comment to `Diff`.
```suggestion
// Diff diffs two Set objects and returns a DiffResult object containing the diffs.
//
// The DiffResult object will contain the elements from newSet on the Modified field.
func (h *SetDiff) Diff(oldSet, newSet *schema.Set) (*DiffResult, error) {
```

File: fastly/diff.go [hunk 11]
```diff
@@ -0,0 +1,110 @@
...
+	return fmt.Errorf("error computing the key for element %v, %v", elem, err)
+}
+
+// DiffResult contains the differences between two sets
+type DiffResult struct {
+	Added      []interface{}
+	Modified   []interface{}
+	Deleted    []interface{}
+	Unmodified []interface{}
+}
```
Comment (phamann) [inline fastly/diff.go]: I'd prefer to see this type definition towards the top of the file above the `Diff` func which uses it.

File: fastly/diff.go (hunk 6 above)
Comment (phamann) [reply fastly/diff.go:1]: While that would be nice, i'm happy for it to remain in this PR due to our time constraints.

File: fastly/convert.go (hunk 4 above)
Comment (phamann) [reply fastly/convert.go]: I'd prefer `uintOrDefault` too. 👍

File: fastly/block_fastly_service_v1_backend.go [hunk 12]
```diff
@@ -33,17 +33,21 @@ func (h *BackendServiceAttributeHandler) Process(d *schema.ResourceData, latestV
...
+
+	setDiff := NewSetDiff(func(backend interface{}) (interface{}, error) {
+		// Use the backend name as key
+		return backend.(map[string]interface{})["name"], nil
+	})
+
+	diffResult, err := setDiff.Diff(obs, nbs)
+	if err != nil {
+		return err
+	}
```
Comment (phamann) [inline fastly/block_fastly_service_v1_backend.go:45]: Nice. Much cleaner than my hacky implementation 👍

**Review by phamann — CHANGES_REQUESTED** [review]
Looking great! Some minor comments and some of @mccurdyc's suggestions still need to be addressed.

File: fastly/diff.go (hunk 10 above)
Comment (matpimenta) [reply fastly/diff.go]: I did some refactoring and the comments got outdated. I'll fix the comments

**Comment by matpimenta** [comment]
<details><summary>Acceptance Tests</summary>
<p>

```
=== RUN   TestResourceFastlyFlattenAcl
--- PASS: TestResourceFastlyFlattenAcl (0.00s)
=== RUN   TestResourceFastlyFlattenBlobStorage
--- PASS: TestResourceFastlyFlattenBlobStorage (0.00s)
=== RUN   TestResourceFastlyFlattenBigQuery
--- PASS: TestResourceFastlyFlattenBigQuery (0.69s)
=== RUN   TestAccFastlyServiceV1_blobstoragelogging_basic_compute
--- PASS: TestAccFastlyServiceV1_blobstoragelogging_basic_compute (63.99s)
=== RUN   TestAccFastlyServiceV1_bigquerylogging_compute
--- PASS: TestAccFastlyServiceV1_bigquerylogging_compute (71.66s)
=== RUN   TestResourceFastlyFlattenCacheSettings
--- PASS: TestResourceFastlyFlattenCacheSettings (0.00s)
=== RUN   TestResourceFastlyFlattenConditions
--- PASS: TestResourceFastlyFlattenConditions (0.00s)
=== RUN   TestAccFastlyServiceV1_bigquerylogging_env
--- PASS: TestAccFastlyServiceV1_bigquerylogging_env (91.89s)
=== RUN   TestResourceFastlyFlattenDictionary
--- PASS: TestResourceFastlyFlattenDictionary (0.00s)
=== RUN   TestAccFastlyServiceV1_blobstoragelogging_env
--- PASS: TestAccFastlyServiceV1_blobstoragelogging_env (88.01s)
=== RUN   TestAccFastlyServiceV1_acl
--- PASS: TestAccFastlyServiceV1_acl (92.66s)
=== RUN   TestAccFastlyServiceV1_blobstoragelogging_default
--- PASS: TestAccFastlyServiceV1_blobstoragelogging_default (90.10s)
=== RUN   TestAccFastlyServiceV1_bigquerylogging
--- PASS: TestAccFastlyServiceV1_bigquerylogging (96.01s)
=== RUN   TestResourceFastlyFlattenDirectors
--- PASS: TestResourceFastlyFlattenDirectors (0.00s)
=== RUN   TestAccFastlyServiceV1_conditional_basic
--- PASS: TestAccFastlyServiceV1_conditional_basic (89.21s)
=== RUN   TestResourceFastlyFlattenDynamicSnippets
--- PASS: TestResourceFastlyFlattenDynamicSnippets (0.00s)
=== RUN   TestAccFastlyServiceV1_dictionary
--- PASS: TestAccFastlyServiceV1_dictionary (81.82s)
=== RUN   TestResourceFastlyFlattenGCS
--- PASS: TestResourceFastlyFlattenGCS (0.09s)
=== RUN   TestAccFastlyServiceV1_blobstoragelogging_basic
--- PASS: TestAccFastlyServiceV1_blobstoragelogging_basic (185.19s)
=== RUN   TestAccFastlyServiceV1_dictionary_write_only
--- PASS: TestAccFastlyServiceV1_dictionary_write_only (87.20s)
=== RUN   TestAccFastlyServiceV1CacheSetting_basic
--- PASS: TestAccFastlyServiceV1CacheSetting_basic (166.73s)
=== RUN   TestResourceFastlyFlattenGzips
--- PASS: TestResourceFastlyFlattenGzips (0.00s)
=== RUN   TestAccFastlyServiceV1_gcslogging_compute
--- PASS: TestAccFastlyServiceV1_gcslogging_compute (73.30s)
=== RUN   TestResourceFastlyFlattenHeaders
--- PASS: TestResourceFastlyFlattenHeaders (0.00s)
=== RUN   TestFastlyServiceV1_BuildHeaders
--- PASS: TestFastlyServiceV1_BuildHeaders (0.00s)
=== RUN   TestAccFastlyServiceV1_gcslogging_env
--- PASS: TestAccFastlyServiceV1_gcslogging_env (83.03s)
=== RUN   TestAccFastlyServiceV1_gcslogging
--- PASS: TestAccFastlyServiceV1_gcslogging (85.18s)
=== RUN   TestAccFastlyServiceV1_dictionary_update_name
--- PASS: TestAccFastlyServiceV1_dictionary_update_name (174.60s)
=== RUN   TestResourceFastlyFlattenHealthChecks
--- PASS: TestResourceFastlyFlattenHealthChecks (0.00s)
=== RUN   TestResourceFastlyFlattenHTTPS
--- PASS: TestResourceFastlyFlattenHTTPS (0.00s)
=== RUN   TestAccFastlyServiceV1_dictionary_update_write_only
--- PASS: TestAccFastlyServiceV1_dictionary_update_write_only (184.80s)
=== RUN   TestResourceFastlyFlattenLogentries
--- PASS: TestResourceFastlyFlattenLogentries (0.00s)
=== RUN   TestAccFastlyServiceV1_directors_basic
--- PASS: TestAccFastlyServiceV1_directors_basic (228.89s)
=== RUN   TestAccFastlyServiceV1_httpslogging_basic_compute
--- PASS: TestAccFastlyServiceV1_httpslogging_basic_compute (76.68s)
=== RUN   TestAccFastlyServiceV1DynamicSnippet_basic
--- PASS: TestAccFastlyServiceV1DynamicSnippet_basic (187.77s)
=== RUN   TestResourceFastlyFlattenCloudfiles
--- PASS: TestResourceFastlyFlattenCloudfiles (0.00s)
=== RUN   TestAccFastlyServiceV1_logentries_basic_compute
--- PASS: TestAccFastlyServiceV1_logentries_basic_compute (76.90s)
=== RUN   TestAccFastlyServiceV1_gzips_basic
--- PASS: TestAccFastlyServiceV1_gzips_basic (183.52s)
=== RUN   TestResourceFastlyFlattenDatadog
--- PASS: TestResourceFastlyFlattenDatadog (0.00s)
=== RUN   TestAccFastlyServiceV1_logentries_formatVersion
--- PASS: TestAccFastlyServiceV1_logentries_formatVersion (83.91s)
=== RUN   TestAccFastlyServiceV1_healthcheck_basic
--- PASS: TestAccFastlyServiceV1_healthcheck_basic (182.70s)
=== RUN   TestResourceFastlyFlattenDigitalOcean
--- PASS: TestResourceFastlyFlattenDigitalOcean (0.00s)
=== RUN   TestAccFastlyServiceV1_httpslogging_basic
--- PASS: TestAccFastlyServiceV1_httpslogging_basic (185.59s)
=== RUN   TestAccFastlyServiceV1_headers_basic
--- PASS: TestAccFastlyServiceV1_headers_basic (217.48s)
=== RUN   TestResourceFastlyFlattenElasticsearch
--- PASS: TestResourceFastlyFlattenElasticsearch (0.00s)
=== RUN   TestAccFastlyServiceV1_logging_cloudfiles_basic_compute
--- PASS: TestAccFastlyServiceV1_logging_cloudfiles_basic_compute (82.23s)
=== RUN   TestAccFastlyServiceV1_logging_datadog_basic_compute
--- PASS: TestAccFastlyServiceV1_logging_datadog_basic_compute (75.09s)
=== RUN   TestResourceFastlyFlattenFTP
--- PASS: TestResourceFastlyFlattenFTP (0.00s)
=== RUN   TestAccFastlyServiceV1_logging_digitalocean_basic_compute
--- PASS: TestAccFastlyServiceV1_logging_digitalocean_basic_compute (66.29s)
=== RUN   TestAccFastlyServiceV1_logging_cloudfiles_basic
--- PASS: TestAccFastlyServiceV1_logging_cloudfiles_basic (190.71s)
=== RUN   TestResourceFastlyFlattenGooglePubSub
--- PASS: TestResourceFastlyFlattenGooglePubSub (0.00s)
=== RUN   TestAccFastlyServiceV1_logging_elasticsearch_basic_compute
--- PASS: TestAccFastlyServiceV1_logging_elasticsearch_basic_compute (69.29s)
=== RUN   TestAccFastlyServiceV1_logentries_basic
--- PASS: TestAccFastlyServiceV1_logentries_basic (297.97s)
=== RUN   TestResourceFastlyFlattenHeroku
--- PASS: TestResourceFastlyFlattenHeroku (0.00s)
=== RUN   TestAccFastlyServiceV1_logging_ftp_basic_compute
--- PASS: TestAccFastlyServiceV1_logging_ftp_basic_compute (70.41s)
=== RUN   TestAccFastlyServiceV1_logging_datadog_basic
--- PASS: TestAccFastlyServiceV1_logging_datadog_basic (183.71s)
=== RUN   TestResourceFastlyFlattenHoneycomb
--- PASS: TestResourceFastlyFlattenHoneycomb (0.00s)
=== RUN   TestAccFastlyServiceV1_googlepubsublogging_basic_compute
--- PASS: TestAccFastlyServiceV1_googlepubsublogging_basic_compute (67.44s)
=== RUN   TestAccFastlyServiceV1_logging_digitalocean_basic
--- PASS: TestAccFastlyServiceV1_logging_digitalocean_basic (179.70s)
=== RUN   TestResourceFastlyFlattenKafka
--- PASS: TestResourceFastlyFlattenKafka (0.00s)
=== RUN   TestAccFastlyServiceV1_logging_elasticsearch_basic
--- PASS: TestAccFastlyServiceV1_logging_elasticsearch_basic (183.86s)
=== RUN   TestAccFastlyServiceV1_logging_heroku_basic_compute
--- PASS: TestAccFastlyServiceV1_logging_heroku_basic_compute (69.14s)
=== RUN   TestResourceFastlyFlattenLoggly
--- PASS: TestResourceFastlyFlattenLoggly (0.00s)
=== RUN   TestAccFastlyServiceV1_logging_honeycomb_basic_compute
--- PASS: TestAccFastlyServiceV1_logging_honeycomb_basic_compute (72.35s)
=== RUN   TestAccFastlyServiceV1_logging_ftp_basic
--- PASS: TestAccFastlyServiceV1_logging_ftp_basic (191.78s)
=== RUN   TestResourceFastlyFlattenLogshuttle
--- PASS: TestResourceFastlyFlattenLogshuttle (0.00s)
=== RUN   TestAccFastlyServiceV1_googlepubsublogging_basic
--- PASS: TestAccFastlyServiceV1_googlepubsublogging_basic (191.36s)
=== RUN   TestAccFastlyServiceV1_kafkalogging_basic_compute
--- PASS: TestAccFastlyServiceV1_kafkalogging_basic_compute (81.14s)
=== RUN   TestResourceFastlyFlattenNewRelic
--- PASS: TestResourceFastlyFlattenNewRelic (0.00s)
=== RUN   TestAccFastlyServiceV1_logging_heroku_basic
--- PASS: TestAccFastlyServiceV1_logging_heroku_basic (192.81s)
=== RUN   TestAccFastlyServiceV1_logging_loggly_basic_compute
--- PASS: TestAccFastlyServiceV1_logging_loggly_basic_compute (69.21s)
=== RUN   TestResourceFastlyFlattenOpenstack
--- PASS: TestResourceFastlyFlattenOpenstack (0.00s)
=== RUN   TestAccFastlyServiceV1_logging_honeycomb_basic
--- PASS: TestAccFastlyServiceV1_logging_honeycomb_basic (180.03s)
=== RUN   TestAccFastlyServiceV1_logging_logshuttle_basic_compute
--- PASS: TestAccFastlyServiceV1_logging_logshuttle_basic_compute (69.80s)
=== RUN   TestResourceFastlyFlattenScalyr
--- PASS: TestResourceFastlyFlattenScalyr (0.00s)
=== RUN   TestAccFastlyServiceV1_kafkalogging_basic
--- PASS: TestAccFastlyServiceV1_kafkalogging_basic (188.84s)
=== RUN   TestAccFastlyServiceV1_logging_newrelic_basic_compute
--- PASS: TestAccFastlyServiceV1_logging_newrelic_basic_compute (76.94s)
=== RUN   TestResourceFastlyFlattenSFTP
--- PASS: TestResourceFastlyFlattenSFTP (0.00s)
=== RUN   TestAccFastlyServiceV1_logging_openstack_basic_compute
--- PASS: TestAccFastlyServiceV1_logging_openstack_basic_compute (71.22s)
=== RUN   TestAccFastlyServiceV1_logging_loggly_basic
--- PASS: TestAccFastlyServiceV1_logging_loggly_basic (193.61s)
=== RUN   TestAccFastlyServiceV1_logging_sftp_password_secret_key
--- PASS: TestAccFastlyServiceV1_logging_sftp_password_secret_key (9.14s)
=== RUN   TestAccFastlyServiceV1_scalyrlogging_basic_compute
--- PASS: TestAccFastlyServiceV1_scalyrlogging_basic_compute (65.89s)
=== RUN   TestResourceFastlyFlattenPapertrail
--- PASS: TestResourceFastlyFlattenPapertrail (0.00s)
=== RUN   TestAccFastlyServiceV1_logging_logshuttle_basic
--- PASS: TestAccFastlyServiceV1_logging_logshuttle_basic (188.00s)
=== RUN   TestAccFastlyServiceV1_logging_newrelic_basic
--- PASS: TestAccFastlyServiceV1_logging_newrelic_basic (177.67s)
=== RUN   TestResourceFastlyFlattenRequestSettings
--- PASS: TestResourceFastlyFlattenRequestSettings (0.00s)
=== RUN   TestAccFastlyServiceV1_logging_sftp_basic_compute
--- PASS: TestAccFastlyServiceV1_logging_sftp_basic_compute (66.58s)
=== RUN   TestResourceFastlyFlattenResponseObjects
--- PASS: TestResourceFastlyFlattenResponseObjects (0.00s)
=== RUN   TestAccFastlyServiceV1_logging_openstack_basic
--- PASS: TestAccFastlyServiceV1_logging_openstack_basic (191.83s)
=== RUN   TestResourceFastlyFlattenS3
--- PASS: TestResourceFastlyFlattenS3 (0.00s)
=== RUN   TestAccFastlyServiceV1_papertrail_basic_compute
--- PASS: TestAccFastlyServiceV1_papertrail_basic_compute (79.06s)
=== RUN   TestAccFastlyServiceV1_scalyrlogging_basic
--- PASS: TestAccFastlyServiceV1_scalyrlogging_basic (182.88s)
=== RUN   TestAccFastlyServiceV1RequestSetting_basic
--- PASS: TestAccFastlyServiceV1RequestSetting_basic (93.46s)
=== RUN   TestAccFastlyServiceV1_logging_sftp_basic
--- PASS: TestAccFastlyServiceV1_logging_sftp_basic (201.37s)
=== RUN   TestAccFastlyServiceV1_s3logging_basic_compute
--- PASS: TestAccFastlyServiceV1_s3logging_basic_compute (84.35s)
=== RUN   TestResourceFastlyFlattenSnippets
--- PASS: TestResourceFastlyFlattenSnippets (0.00s)
=== RUN   TestAccFastlyServiceV1_papertrail_basic
--- PASS: TestAccFastlyServiceV1_papertrail_basic (185.19s)
=== RUN   TestResourceFastlyFlattenSplunk
--- PASS: TestResourceFastlyFlattenSplunk (0.15s)
=== RUN   TestAccFastlyServiceV1_package_basic
--- PASS: TestAccFastlyServiceV1_package_basic (222.83s)
=== RUN   TestAccFastlyServiceV1_s3logging_domain_default
--- PASS: TestAccFastlyServiceV1_s3logging_domain_default (101.41s)
=== RUN   TestAccFastlyServiceV1_s3logging_s3_env
--- PASS: TestAccFastlyServiceV1_s3logging_s3_env (82.78s)
=== RUN   TestAccFastlyServiceV1_response_object_basic
--- PASS: TestAccFastlyServiceV1_response_object_basic (178.22s)
=== RUN   TestAccFastlyServiceV1_s3logging_formatVersion
--- PASS: TestAccFastlyServiceV1_s3logging_formatVersion (85.64s)
=== RUN   TestResourceFastlyFlattenSumologic
--- PASS: TestResourceFastlyFlattenSumologic (0.00s)
=== RUN   TestAccFastlyServiceV1_splunk_basic_compute
--- PASS: TestAccFastlyServiceV1_splunk_basic_compute (67.83s)
=== RUN   TestAccFastlyServiceV1_s3logging_basic
--- PASS: TestAccFastlyServiceV1_s3logging_basic (198.45s)
=== RUN   TestResourceFastlyFlattenSyslog
--- PASS: TestResourceFastlyFlattenSyslog (0.50s)
=== RUN   TestAccFastlyServiceV1_splunk_default
--- PASS: TestAccFastlyServiceV1_splunk_default (90.66s)
=== RUN   TestAccFastlyServiceV1_splunk_env
--- PASS: TestAccFastlyServiceV1_splunk_env (90.26s)
=== RUN   TestAccFastlyServiceV1_sumologic_compute
--- PASS: TestAccFastlyServiceV1_sumologic_compute (68.59s)
=== RUN   TestAccFastlyServiceV1Snippet_basic
--- PASS: TestAccFastlyServiceV1Snippet_basic (169.80s)
=== RUN   TestResourceFastlyFlattenVCLs
--- PASS: TestResourceFastlyFlattenVCLs (0.00s)
=== RUN   TestAccFastlyServiceV1_syslog_basic_compute
--- PASS: TestAccFastlyServiceV1_syslog_basic_compute (60.38s)
=== RUN   TestResourceFastlyFlattenWAF
--- PASS: TestResourceFastlyFlattenWAF (0.00s)
=== RUN   TestAccFastlyServiceV1_splunk_basic
--- PASS: TestAccFastlyServiceV1_splunk_basic (183.18s)
=== RUN   TestAccFastlyServiceV1_splunk_complete
--- PASS: TestAccFastlyServiceV1_splunk_complete (171.44s)
=== RUN   TestAccFastlyServiceV1_syslog_formatVersion
--- PASS: TestAccFastlyServiceV1_syslog_formatVersion (88.02s)
=== RUN   TestAccFastlyServiceV1_sumologic
--- PASS: TestAccFastlyServiceV1_sumologic (173.39s)
=== RUN   TestAccFastlyServiceWAFVersionV1FlattenWAFActiveRules
--- PASS: TestAccFastlyServiceWAFVersionV1FlattenWAFActiveRules (0.00s)
=== RUN   TestAccFastlyServiceWAFVersionV1FlattenWAFDeleteByModSecID
--- PASS: TestAccFastlyServiceWAFVersionV1FlattenWAFDeleteByModSecID (0.00s)
=== RUN   TestAccFastlyServiceV1_syslog_useTls
--- PASS: TestAccFastlyServiceV1_syslog_useTls (89.42s)
=== RUN   TestAccFastlyServiceV1_syslog_basic
--- PASS: TestAccFastlyServiceV1_syslog_basic (166.47s)
=== RUN   TestAccFastlyServiceV1WAFAdd
=== PAUSE TestAccFastlyServiceV1WAFAdd
=== CONT  TestAccFastlyServiceV1WAFAdd
--- PASS: TestAccFastlyServiceV1WAFAdd (91.39s)
=== RUN   TestAccFastlyServiceV1_VCL_basic
--- PASS: TestAccFastlyServiceV1_VCL_basic (172.00s)
=== RUN   TestUserAgentContainsProviderVersion
--- PASS: TestUserAgentContainsProviderVersion (0.00s)
=== RUN   TestStringPtr
--- PASS: TestStringPtr (0.00s)
=== RUN   TestIntPtr
--- PASS: TestIntPtr (0.00s)
=== RUN   TestBoolPtr
--- PASS: TestBoolPtr (0.00s)
=== RUN   TestDefaultUintToZero
--- PASS: TestDefaultUintToZero (0.00s)
=== RUN   TestDefaultUint
--- PASS: TestDefaultUint (0.00s)
=== RUN   TestAccFastlyIPRanges
--- PASS: TestAccFastlyIPRanges (3.45s)
=== RUN   TestAccFastlyWAFRulesDetermineRevision
--- PASS: TestAccFastlyWAFRulesDetermineRevision (0.00s)
=== RUN   TestAccFastlyWAFRulesFlattenWAFRules
--- PASS: TestAccFastlyWAFRulesFlattenWAFRules (0.00s)
=== RUN   TestAccFastlyServiceV1WAFUpdateResponse
=== PAUSE TestAccFastlyServiceV1WAFUpdateResponse
=== CONT  TestAccFastlyServiceV1WAFUpdateResponse
--- PASS: TestAccFastlyServiceV1WAFUpdateResponse (178.95s)
=== RUN   TestAccFastlyWAFRulesExcludeFilter
--- PASS: TestAccFastlyWAFRulesExcludeFilter (5.63s)
=== RUN   TestAccFastlyServiceV1WAFUpdateCondition
=== PAUSE TestAccFastlyServiceV1WAFUpdateCondition
=== CONT  TestAccFastlyServiceV1WAFUpdateCondition
--- PASS: TestAccFastlyServiceV1WAFUpdateCondition (179.64s)
=== RUN   TestAccFastlyWAFRulesPublisherFilter
--- PASS: TestAccFastlyWAFRulesPublisherFilter (23.45s)
=== RUN   TestAccFastlyServiceWAFVersionV1AddWithRules
=== PAUSE TestAccFastlyServiceWAFVersionV1AddWithRules
=== CONT  TestAccFastlyServiceWAFVersionV1AddWithRules
--- PASS: TestAccFastlyServiceWAFVersionV1AddWithRules (151.78s)
=== RUN   TestAccFastlyWAFRulesTagFilter
--- PASS: TestAccFastlyWAFRulesTagFilter (5.35s)
=== RUN   TestEscapePercentSign
=== RUN   TestEscapePercentSign/string_no_percent_signs_should_change_nothing
=== RUN   TestEscapePercentSign/one_percent_sign_should_return_two_percent_signs
=== RUN   TestEscapePercentSign/one_percent_sign_mid-string_should_return_two_percent_signs_in_the_same_place
=== RUN   TestEscapePercentSign/one_percent_sign_before_left_curly_brace_should_return_four_percent_signs_then_curly_brace
--- PASS: TestEscapePercentSign (0.00s)
    --- PASS: TestEscapePercentSign/string_no_percent_signs_should_change_nothing (0.00s)
    --- PASS: TestEscapePercentSign/one_percent_sign_should_return_two_percent_signs (0.00s)
    --- PASS: TestEscapePercentSign/one_percent_sign_mid-string_should_return_two_percent_signs_in_the_same_place (0.00s)
    --- PASS: TestEscapePercentSign/one_percent_sign_before_left_curly_brace_should_return_four_percent_signs_then_curly_brace (0.00s)
=== RUN   TestSetDiff_Diff
=== RUN   TestSetDiff_Diff/should_return_the_correct_diff
=== RUN   TestSetDiff_Diff/should_diff_empty_element_lists
=== RUN   TestSetDiff_Diff/should_return_error_if_key_cannot_be_computed
--- PASS: TestSetDiff_Diff (0.00s)
    --- PASS: TestSetDiff_Diff/should_return_the_correct_diff (0.00s)
    --- PASS: TestSetDiff_Diff/should_diff_empty_element_lists (0.00s)
    --- PASS: TestSetDiff_Diff/should_return_error_if_key_cannot_be_computed (0.00s)
=== RUN   TestProvider
--- PASS: TestProvider (0.01s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestResourceFastlyFlattenAclEntries
--- PASS: TestResourceFastlyFlattenAclEntries (0.00s)
=== RUN   TestAccFastlyServiceWAFVersionV1ImportWithRules
--- PASS: TestAccFastlyServiceWAFVersionV1ImportWithRules (151.35s)
=== RUN   TestAccFastlyServiceV1WAFAddAndRemove
=== PAUSE TestAccFastlyServiceV1WAFAddAndRemove
=== CONT  TestAccFastlyServiceV1WAFAddAndRemove
--- PASS: TestAccFastlyServiceV1WAFAddAndRemove (263.46s)
=== RUN   TestAccFastlyServiceAclEntriesV1_create
--- PASS: TestAccFastlyServiceAclEntriesV1_create (94.58s)
=== RUN   TestResourceFastlyFlattenBackendCompute
--- PASS: TestResourceFastlyFlattenBackendCompute (0.00s)
=== RUN   TestAccFastlyServiceAclEntriesV1_import
--- PASS: TestAccFastlyServiceAclEntriesV1_import (91.80s)
=== RUN   TestAccFastlyServiceWAFVersionV1DeleteRules
=== PAUSE TestAccFastlyServiceWAFVersionV1DeleteRules
=== CONT  TestAccFastlyServiceWAFVersionV1DeleteRules
--- PASS: TestAccFastlyServiceWAFVersionV1DeleteRules (263.15s)
=== RUN   TestAccFastlyServiceCompute_basic
--- PASS: TestAccFastlyServiceCompute_basic (15.92s)
=== RUN   TestResourceFastlyFlattenDictionaryItems
--- PASS: TestResourceFastlyFlattenDictionaryItems (0.00s)
=== RUN   TestAccFastlyServiceWAFVersionV1UpdateRules
=== PAUSE TestAccFastlyServiceWAFVersionV1UpdateRules
=== CONT  TestAccFastlyServiceWAFVersionV1UpdateRules
--- PASS: TestAccFastlyServiceWAFVersionV1UpdateRules (286.13s)
=== RUN   TestAccFastlyServiceCompute_import
--- PASS: TestAccFastlyServiceCompute_import (33.22s)
=== RUN   TestAccFastlyServiceAclEntriesV1_update
--- PASS: TestAccFastlyServiceAclEntriesV1_update (179.64s)
=== RUN   TestAccFastlyServiceAclEntriesV1_update_additional_fields
--- PASS: TestAccFastlyServiceAclEntriesV1_update_additional_fields (190.42s)
=== RUN   TestAccFastlyServiceAclEntriesV1_delete
--- PASS: TestAccFastlyServiceAclEntriesV1_delete (188.52s)
=== RUN   TestAccFastlyServiceAclEntriesV1_process_1001_entries
--- PASS: TestAccFastlyServiceAclEntriesV1_process_1001_entries (164.11s)
=== RUN   TestAccFastlyServiceDictionaryItemV1_create_dynamic
--- PASS: TestAccFastlyServiceDictionaryItemV1_create_dynamic (89.77s)
=== RUN   TestAccFastlyServiceDictionaryItemV1_create
--- PASS: TestAccFastlyServiceDictionaryItemV1_create (93.42s)
=== RUN   TestAccFastlyServiceDictionaryItemV1_import
--- PASS: TestAccFastlyServiceDictionaryItemV1_import (95.78s)
=== RUN   TestAccFastlyServiceDictionaryItemV1_external_item_is_removed
--- PASS: TestAccFastlyServiceDictionaryItemV1_external_item_is_removed (145.37s)
=== RUN   TestAccFastlyServiceDynamicSnippetContentV1_create
--- PASS: TestAccFastlyServiceDynamicSnippetContentV1_create (87.39s)
=== RUN   TestResourceFastlyFlattenDomains
--- PASS: TestResourceFastlyFlattenDomains (0.00s)
=== RUN   TestResourceFastlyFlattenBackend
--- PASS: TestResourceFastlyFlattenBackend (0.00s)
=== RUN   TestAccFastlyServiceDictionaryItemV1_batch_1001_items
--- PASS: TestAccFastlyServiceDictionaryItemV1_batch_1001_items (112.38s)
=== RUN   TestAccFastlyServiceDictionaryItemV1_update
--- PASS: TestAccFastlyServiceDictionaryItemV1_update (184.21s)
=== RUN   TestAccFastlyServiceDictionaryItemV1_external_item_deleted
--- PASS: TestAccFastlyServiceDictionaryItemV1_external_item_deleted (196.27s)
=== RUN   TestAccFastlyServiceDynamicSnippetContentV1_import
--- PASS: TestAccFastlyServiceDynamicSnippetContentV1_import (93.97s)
=== RUN   TestAccFastlyServiceDynamicSnippetContentV1_update
--- PASS: TestAccFastlyServiceDynamicSnippetContentV1_update (180.57s)
=== RUN   TestAccFastlyServiceDynamicSnippetContentV1_external_snippet_is_removed
--- PASS: TestAccFastlyServiceDynamicSnippetContentV1_external_snippet_is_removed (182.03s)
=== RUN   TestAccFastlyServiceV1_updateInvalidBackend
--- PASS: TestAccFastlyServiceV1_updateInvalidBackend (95.15s)
=== RUN   TestAccFastlyServiceV1_disappears
--- PASS: TestAccFastlyServiceV1_disappears (36.19s)
=== RUN   TestAccFastlyServiceDynamicSnippetContentV1_normal_snippet_is_not_removed
--- PASS: TestAccFastlyServiceDynamicSnippetContentV1_normal_snippet_is_not_removed (181.91s)
=== RUN   TestAccFastlyServiceV1_createDefaultTTL
--- PASS: TestAccFastlyServiceV1_createDefaultTTL (79.12s)
=== RUN   TestAccFastlyServiceWAFVersionV1DetermineVersion
--- PASS: TestAccFastlyServiceWAFVersionV1DetermineVersion (0.00s)
=== RUN   TestAccFastlyServiceV1_updateBackend
--- PASS: TestAccFastlyServiceV1_updateBackend (175.96s)
=== RUN   TestAccFastlyServiceV1_updateDomain
--- PASS: TestAccFastlyServiceV1_updateDomain (181.90s)
=== RUN   TestAccFastlyServiceV1_createZeroDefaultTTL
--- PASS: TestAccFastlyServiceV1_createZeroDefaultTTL (84.82s)
=== RUN   TestAccFastlyServiceV1_basic
--- PASS: TestAccFastlyServiceV1_basic (163.65s)
=== RUN   TestAccFastlyServiceV1_import
--- PASS: TestAccFastlyServiceV1_import (132.30s)
=== RUN   TestAccFastlyUserV1_basic
--- PASS: TestAccFastlyUserV1_basic (6.56s)
=== RUN   TestAccFastlyUserV1_updateLogin
--- PASS: TestAccFastlyUserV1_updateLogin (5.41s)
=== RUN   TestAccFastlyServiceV1_creation_with_versionless_resources
--- PASS: TestAccFastlyServiceV1_creation_with_versionless_resources (107.19s)
=== RUN   TestAccFastlyServiceWAFVersionDeploymentStatus
=== RUN   TestAccFastlyServiceWAFVersionDeploymentStatus/Status_
=== RUN   TestAccFastlyServiceWAFVersionDeploymentStatus/Status_failed
=== RUN   TestAccFastlyServiceWAFVersionDeploymentStatus/Status_completed
--- PASS: TestAccFastlyServiceWAFVersionDeploymentStatus (0.43s)
    --- PASS: TestAccFastlyServiceWAFVersionDeploymentStatus/Status_ (0.00s)
    --- PASS: TestAccFastlyServiceWAFVersionDeploymentStatus/Status_failed (0.00s)
    --- PASS: TestAccFastlyServiceWAFVersionDeploymentStatus/Status_completed (0.43s)
=== RUN   TestValidateLoggingFormatVersion
=== RUN   TestValidateLoggingFormatVersion/3
=== RUN   TestValidateLoggingFormatVersion/4
=== RUN   TestValidateLoggingFormatVersion/5
=== RUN   TestValidateLoggingFormatVersion/0
=== RUN   TestValidateLoggingFormatVersion/1
=== RUN   TestValidateLoggingFormatVersion/2
--- PASS: TestValidateLoggingFormatVersion (0.00s)
    --- PASS: TestValidateLoggingFormatVersion/3 (0.00s)
    --- PASS: TestValidateLoggingFormatVersion/4 (0.00s)
    --- PASS: TestValidateLoggingFormatVersion/5 (0.00s)
    --- PASS: TestValidateLoggingFormatVersion/0 (0.00s)
    --- PASS: TestValidateLoggingFormatVersion/1 (0.00s)
    --- PASS: TestValidateLoggingFormatVersion/2 (0.00s)
=== RUN   TestValidateLoggingMessageType
=== RUN   TestValidateLoggingMessageType/classic
=== RUN   TestValidateLoggingMessageType/loggly
=== RUN   TestValidateLoggingMessageType/logplex
=== RUN   TestValidateLoggingMessageType/blank
=== RUN   TestValidateLoggingMessageType/CLASSIC
=== RUN   TestValidateLoggingMessageType/LOGGLY
=== RUN   TestValidateLoggingMessageType/LOGPLEX
=== RUN   TestValidateLoggingMessageType/BLANK
--- PASS: TestValidateLoggingMessageType (0.00s)
    --- PASS: TestValidateLoggingMessageType/classic (0.00s)
    --- PASS: TestValidateLoggingMessageType/loggly (0.00s)
    --- PASS: TestValidateLoggingMessageType/logplex (0.00s)
    --- PASS: TestValidateLoggingMessageType/blank (0.00s)
    --- PASS: TestValidateLoggingMessageType/CLASSIC (0.00s)
    --- PASS: TestValidateLoggingMessageType/LOGGLY (0.00s)
    --- PASS: TestValidateLoggingMessageType/LOGPLEX (0.00s)
    --- PASS: TestValidateLoggingMessageType/BLANK (0.00s)
=== RUN   TestValidateLoggingPlacement
=== RUN   TestValidateLoggingPlacement/none
=== RUN   TestValidateLoggingPlacement/waf_debug
=== RUN   TestValidateLoggingPlacement/NONE
=== RUN   TestValidateLoggingPlacement/WAF_DEBUG
--- PASS: TestValidateLoggingPlacement (0.00s)
    --- PASS: TestValidateLoggingPlacement/none (0.00s)
    --- PASS: TestValidateLoggingPlacement/waf_debug (0.00s)
    --- PASS: TestValidateLoggingPlacement/NONE (0.00s)
    --- PASS: TestValidateLoggingPlacement/WAF_DEBUG (0.00s)
=== RUN   TestValidateLoggingServerSideEncryption
=== RUN   TestValidateLoggingServerSideEncryption/AES256
=== RUN   TestValidateLoggingServerSideEncryption/aws:kms
=== RUN   TestValidateLoggingServerSideEncryption/aes256
=== RUN   TestValidateLoggingServerSideEncryption/AWS:KMS
=== RUN   TestValidateLoggingServerSideEncryption/aws:KMS
=== RUN   TestValidateLoggingServerSideEncryption/AWS:kms
--- PASS: TestValidateLoggingServerSideEncryption (0.00s)
    --- PASS: TestValidateLoggingServerSideEncryption/AES256 (0.00s)
    --- PASS: TestValidateLoggingServerSideEncryption/aws:kms (0.00s)
    --- PASS: TestValidateLoggingServerSideEncryption/aes256 (0.00s)
    --- PASS: TestValidateLoggingServerSideEncryption/AWS:KMS (0.00s)
    --- PASS: TestValidateLoggingServerSideEncryption/aws:KMS (0.00s)
    --- PASS: TestValidateLoggingServerSideEncryption/AWS:kms (0.00s)
=== RUN   TestValidateDirectorQuorum
=== RUN   TestValidateDirectorQuorum/101
=== RUN   TestValidateDirectorQuorum/150
=== RUN   TestValidateDirectorQuorum/0
=== RUN   TestValidateDirectorQuorum/55
=== RUN   TestValidateDirectorQuorum/100
=== RUN   TestValidateDirectorQuorum/-1
--- PASS: TestValidateDirectorQuorum (0.00s)
    --- PASS: TestValidateDirectorQuorum/101 (0.00s)
    --- PASS: TestValidateDirectorQuorum/150 (0.00s)
    --- PASS: TestValidateDirectorQuorum/0 (0.00s)
    --- PASS: TestValidateDirectorQuorum/55 (0.00s)
    --- PASS: TestValidateDirectorQuorum/100 (0.00s)
    --- PASS: TestValidateDirectorQuorum/-1 (0.00s)
=== RUN   TestValidateDirectorType
=== RUN   TestValidateDirectorType/3
=== RUN   TestValidateDirectorType/4
=== RUN   TestValidateDirectorType/5
=== RUN   TestValidateDirectorType/0
=== RUN   TestValidateDirectorType/1
=== RUN   TestValidateDirectorType/2
--- PASS: TestValidateDirectorType (0.00s)
    --- PASS: TestValidateDirectorType/3 (0.00s)
    --- PASS: TestValidateDirectorType/4 (0.00s)
    --- PASS: TestValidateDirectorType/5 (0.00s)
    --- PASS: TestValidateDirectorType/0 (0.00s)
    --- PASS: TestValidateDirectorType/1 (0.00s)
    --- PASS: TestValidateDirectorType/2 (0.00s)
=== RUN   TestValidateConditionType
=== RUN   TestValidateConditionType/REQUEST
=== RUN   TestValidateConditionType/RESPONSE
=== RUN   TestValidateConditionType/CACHE
=== RUN   TestValidateConditionType/PREFETCH
=== RUN   TestValidateConditionType/request
=== RUN   TestValidateConditionType/response
=== RUN   TestValidateConditionType/cache
=== RUN   TestValidateConditionType/prefetch
--- PASS: TestValidateConditionType (0.00s)
    --- PASS: TestValidateConditionType/REQUEST (0.00s)
    --- PASS: TestValidateConditionType/RESPONSE (0.00s)
    --- PASS: TestValidateConditionType/CACHE (0.00s)
    --- PASS: TestValidateConditionType/PREFETCH (0.00s)
    --- PASS: TestValidateConditionType/request (0.00s)
    --- PASS: TestValidateConditionType/response (0.00s)
    --- PASS: TestValidateConditionType/cache (0.00s)
    --- PASS: TestValidateConditionType/prefetch (0.00s)
=== RUN   TestValidateHeaderAction
=== RUN   TestValidateHeaderAction/set
=== RUN   TestValidateHeaderAction/append
=== RUN   TestValidateHeaderAction/delete
=== RUN   TestValidateHeaderAction/regex
=== RUN   TestValidateHeaderAction/regex_repeat
=== RUN   TestValidateHeaderAction/SET
=== RUN   TestValidateHeaderAction/APPEND
=== RUN   TestValidateHeaderAction/DELETE
=== RUN   TestValidateHeaderAction/REGEX
=== RUN   TestValidateHeaderAction/REGEX_REPEAT
--- PASS: TestValidateHeaderAction (0.00s)
    --- PASS: TestValidateHeaderAction/set (0.00s)
    --- PASS: TestValidateHeaderAction/append (0.00s)
    --- PASS: TestValidateHeaderAction/delete (0.00s)
    --- PASS: TestValidateHeaderAction/regex (0.00s)
    --- PASS: TestValidateHeaderAction/regex_repeat (0.00s)
    --- PASS: TestValidateHeaderAction/SET (0.00s)
    --- PASS: TestValidateHeaderAction/APPEND (0.00s)
    --- PASS: TestValidateHeaderAction/DELETE (0.00s)
    --- PASS: TestValidateHeaderAction/REGEX (0.00s)
    --- PASS: TestValidateHeaderAction/REGEX_REPEAT (0.00s)
=== RUN   TestValidateHeaderType
=== RUN   TestValidateHeaderType/request
=== RUN   TestValidateHeaderType/fetch
=== RUN   TestValidateHeaderType/cache
=== RUN   TestValidateHeaderType/response
=== RUN   TestValidateHeaderType/REQUEST
=== RUN   TestValidateHeaderType/FETCH
=== RUN   TestValidateHeaderType/CACHE
=== RUN   TestValidateHeaderType/RESPONSE
--- PASS: TestValidateHeaderType (0.00s)
    --- PASS: TestValidateHeaderType/request (0.00s)
    --- PASS: TestValidateHeaderType/fetch (0.00s)
    --- PASS: TestValidateHeaderType/cache (0.00s)
    --- PASS: TestValidateHeaderType/response (0.00s)
    --- PASS: TestValidateHeaderType/REQUEST (0.00s)
    --- PASS: TestValidateHeaderType/FETCH (0.00s)
    --- PASS: TestValidateHeaderType/CACHE (0.00s)
    --- PASS: TestValidateHeaderType/RESPONSE (0.00s)
=== RUN   TestValidateRuleStatusType
=== RUN   TestValidateRuleStatusType/log
=== RUN   TestValidateRuleStatusType/block
=== RUN   TestValidateRuleStatusType/score
=== RUN   TestValidateRuleStatusType/123
=== RUN   TestValidateRuleStatusType/any
=== RUN   TestValidateRuleStatusType/???
--- PASS: TestValidateRuleStatusType (0.00s)
    --- PASS: TestValidateRuleStatusType/log (0.00s)
    --- PASS: TestValidateRuleStatusType/block (0.00s)
    --- PASS: TestValidateRuleStatusType/score (0.00s)
    --- PASS: TestValidateRuleStatusType/123 (0.00s)
    --- PASS: TestValidateRuleStatusType/any (0.00s)
    --- PASS: TestValidateRuleStatusType/??? (0.00s)
=== RUN   TestValidateSnippetType
=== RUN   TestValidateSnippetType/init
=== RUN   TestValidateSnippetType/recv
=== RUN   TestValidateSnippetType/hit
=== RUN   TestValidateSnippetType/miss
=== RUN   TestValidateSnippetType/pass
=== RUN   TestValidateSnippetType/hash
=== RUN   TestValidateSnippetType/fetch
=== RUN   TestValidateSnippetType/error
=== RUN   TestValidateSnippetType/deliver
=== RUN   TestValidateSnippetType/log
=== RUN   TestValidateSnippetType/none
=== RUN   TestValidateSnippetType/INIT
=== RUN   TestValidateSnippetType/RECV
=== RUN   TestValidateSnippetType/HIT
=== RUN   TestValidateSnippetType/MISS
=== RUN   TestValidateSnippetType/PASS
=== RUN   TestValidateSnippetType/FETCH
=== RUN   TestValidateSnippetType/HASH
=== RUN   TestValidateSnippetType/ERROR
=== RUN   TestValidateSnippetType/DELIVER
=== RUN   TestValidateSnippetType/LOG
=== RUN   TestValidateSnippetType/NONE
--- PASS: TestValidateSnippetType (0.00s)
    --- PASS: TestValidateSnippetType/init (0.00s)
    --- PASS: TestValidateSnippetType/recv (0.00s)
    --- PASS: TestValidateSnippetType/hit (0.00s)
    --- PASS: TestValidateSnippetType/miss (0.00s)
    --- PASS: TestValidateSnippetType/pass (0.00s)
    --- PASS: TestValidateSnippetType/hash (0.00s)
    --- PASS: TestValidateSnippetType/fetch (0.00s)
    --- PASS: TestValidateSnippetType/error (0.00s)
    --- PASS: TestValidateSnippetType/deliver (0.00s)
    --- PASS: TestValidateSnippetType/log (0.00s)
    --- PASS: TestValidateSnippetType/none (0.00s)
    --- PASS: TestValidateSnippetType/INIT (0.00s)
    --- PASS: TestValidateSnippetType/RECV (0.00s)
    --- PASS: TestValidateSnippetType/HIT (0.00s)
    --- PASS: TestValidateSnippetType/MISS (0.00s)
    --- PASS: TestValidateSnippetType/PASS (0.00s)
    --- PASS: TestValidateSnippetType/FETCH (0.00s)
    --- PASS: TestValidateSnippetType/HASH (0.00s)
    --- PASS: TestValidateSnippetType/ERROR (0.00s)
    --- PASS: TestValidateSnippetType/DELIVER (0.00s)
    --- PASS: TestValidateSnippetType/LOG (0.00s)
    --- PASS: TestValidateSnippetType/NONE (0.00s)
=== RUN   TestValidateDictionaryItemMaxSize
=== RUN   TestValidateDictionaryItemMaxSize/Ten_hundred_dictionary_items
=== RUN   TestValidateDictionaryItemMaxSize/Ten_thousand_dictionary_items
=== RUN   TestValidateDictionaryItemMaxSize/Ten_thousand_and_one_dictionary_items
--- PASS: TestValidateDictionaryItemMaxSize (0.01s)
    --- PASS: TestValidateDictionaryItemMaxSize/Ten_hundred_dictionary_items (0.00s)
    --- PASS: TestValidateDictionaryItemMaxSize/Ten_thousand_dictionary_items (0.00s)
    --- PASS: TestValidateDictionaryItemMaxSize/Ten_thousand_and_one_dictionary_items (0.00s)
=== RUN   TestValidateUserRole
=== RUN   TestValidateUserRole/user
=== RUN   TestValidateUserRole/billing
=== RUN   TestValidateUserRole/engineer
=== RUN   TestValidateUserRole/superuser
=== RUN   TestValidateUserRole/USER
=== RUN   TestValidateUserRole/BILLING
=== RUN   TestValidateUserRole/ENGINEER
=== RUN   TestValidateUserRole/SUPERUSER
--- PASS: TestValidateUserRole (0.00s)
    --- PASS: TestValidateUserRole/user (0.00s)
    --- PASS: TestValidateUserRole/billing (0.00s)
    --- PASS: TestValidateUserRole/engineer (0.00s)
    --- PASS: TestValidateUserRole/superuser (0.00s)
    --- PASS: TestValidateUserRole/USER (0.00s)
    --- PASS: TestValidateUserRole/BILLING (0.00s)
    --- PASS: TestValidateUserRole/ENGINEER (0.00s)
    --- PASS: TestValidateUserRole/SUPERUSER (0.00s)
=== RUN   TestValidateHTTPSURL
=== RUN   TestValidateHTTPSURL/https://api.fastly.com
=== RUN   TestValidateHTTPSURL/http://example.com
--- PASS: TestValidateHTTPSURL (0.00s)
    --- PASS: TestValidateHTTPSURL/https://api.fastly.com (0.00s)
    --- PASS: TestValidateHTTPSURL/http://example.com (0.00s)
=== RUN   TestAccFastlyServiceWAFVersionV1Add
=== PAUSE TestAccFastlyServiceWAFVersionV1Add
=== CONT  TestAccFastlyServiceWAFVersionV1Add
--- PASS: TestAccFastlyServiceWAFVersionV1Add (151.25s)
=== RUN   TestAccFastlyServiceV1_defaultTTL
--- PASS: TestAccFastlyServiceV1_defaultTTL (263.32s)
=== RUN   TestAccFastlyServiceWAFVersionV1Delete
=== PAUSE TestAccFastlyServiceWAFVersionV1Delete
=== CONT  TestAccFastlyServiceWAFVersionV1Delete
--- PASS: TestAccFastlyServiceWAFVersionV1Delete (217.26s)
=== RUN   TestAccFastlyServiceWAFVersionV1AddExistingService
=== PAUSE TestAccFastlyServiceWAFVersionV1AddExistingService
=== CONT  TestAccFastlyServiceWAFVersionV1AddExistingService
--- PASS: TestAccFastlyServiceWAFVersionV1AddExistingService (249.27s)
=== RUN   TestAccFastlyServiceWAFVersionV1Import
--- PASS: TestAccFastlyServiceWAFVersionV1Import (197.91s)
=== RUN   TestAccFastlyServiceWAFVersionV1Update
=== PAUSE TestAccFastlyServiceWAFVersionV1Update
=== CONT  TestAccFastlyServiceWAFVersionV1Update
--- PASS: TestAccFastlyServiceWAFVersionV1Update (275.49s)
PASS
```

</p>
</details>

**Review by phamann — APPROVED** [review]
LGTM - Thank you for fixing this with a clean implementation 🎉
